#!/usr/bin/env python3
"""
batch3_p7sst.py — 100 P.7 SST practice questions supplied by the project owner.

ORIGIN NOTE
    These are ORIGINAL practice questions inspired by UNEB-examined curriculum
    areas. They are NOT UNEB past-paper questions and are never labelled as
    such. Every record carries `origin` saying so. The genuine past papers live
    separately in data/papers/.

Wording, options and marked answers are exactly as supplied. Every answer was
fact-checked before inclusion; nothing was silently changed.

This batch is placed FIRST for P7 so it occupies IDs P7_SST_001 … P7_SST_100.
"""
from qhelpers import M

C = "P7"
ORIGIN = "Original practice question (not a UNEB past paper)"

Q = [
 # ── 1–20  GEOGRAPHY OF UGANDA ─────────────────────────────────────────────
 M(C,"Geography","Location of Uganda","Easy","Uganda is located on which continent?",
   ["Asia","Africa","Europe","Australia"],"B",
   "Uganda is a country in East Africa, which is part of the African continent."),
 M(C,"Geography","Neighbouring Countries","Easy","Which country lies to the east of Uganda?",
   ["Kenya","Rwanda","Democratic Republic of Congo","Tanzania"],"A",
   "Kenya borders Uganda on the eastern side."),
 M(C,"Geography","Neighbouring Countries","Easy","Which country borders Uganda to the west?",
   ["Kenya","South Sudan","Democratic Republic of Congo","Tanzania"],"C",
   "The Democratic Republic of Congo lies to the west of Uganda."),
 M(C,"Geography","Neighbouring Countries","Easy","Which country is found to the north of Uganda?",
   ["Rwanda","South Sudan","Tanzania","Kenya"],"B",
   "South Sudan borders Uganda in the north."),
 M(C,"Geography","Neighbouring Countries","Easy","Which country borders Uganda to the south-west?",
   ["Rwanda","Kenya","South Sudan","Ethiopia"],"A",
   "Rwanda lies to the south-west of Uganda."),
 M(C,"Geography","Neighbouring Countries","Easy","Which country lies to the south of Uganda?",
   ["Kenya","Tanzania","South Sudan","Sudan"],"B",
   "Tanzania borders Uganda on the south."),
 M(C,"Geography","Location of Uganda","Easy","What is the capital city of Uganda?",
   ["Entebbe","Jinja","Kampala","Mbarara"],"C",
   "Kampala is the capital and largest city of Uganda."),
 M(C,"Physical Features","Lakes","Easy","Which large lake occupies part of Uganda's southern border?",
   ["Lake Kyoga","Lake Victoria","Lake Albert","Lake Edward"],"B",
   "Lake Victoria lies along Uganda's southern border and is shared with Kenya and Tanzania."),
 M(C,"Physical Features","Rivers","Medium","Which river forms part of Uganda's border with the Democratic Republic of Congo?",
   ["River Nile","River Semliki","River Katonga","River Kafu"],"B",
   "The River Semliki flows between Lake Edward and Lake Albert and forms part of the border with the D.R. Congo."),
 M(C,"Physical Features","Rivers","Easy","Which is the longest river flowing through Uganda?",
   ["River Kagera","River Nile","River Katonga","River Achwa"],"B",
   "The River Nile is the longest river flowing through Uganda."),
 M(C,"Physical Features","Rivers","Easy","The source of the River Nile in Uganda is associated with which lake?",
   ["Lake Kyoga","Lake Albert","Lake Victoria","Lake Edward"],"C",
   "The Nile leaves Lake Victoria at Jinja and flows northwards."),
 M(C,"Physical Features","Mountains","Easy","Which physical feature is found in eastern Uganda?",
   ["Rwenzori Mountains","Mount Elgon","Lake Albert","Lake Edward"],"B",
   "Mount Elgon rises in eastern Uganda on the border with Kenya."),
 M(C,"Physical Features","Mountains","Easy","The Rwenzori Mountains are mainly found in which part of Uganda?",
   ["Western Uganda","Eastern Uganda","Northern Uganda","Central Uganda"],"A",
   "The Rwenzori Mountains lie in western Uganda."),
 M(C,"Physical Features","Mountains","Medium","Which mountain is associated with the border between Uganda and the Democratic Republic of Congo?",
   ["Mount Elgon","Mount Moroto","Rwenzori Mountains","Mount Kadam"],"C",
   "The Rwenzori Mountains lie along the Uganda–D.R. Congo border."),
 M(C,"Physical Features","Importance of Features","Medium","Why are mountains important to people?",
   ["They prevent all rainfall","They provide areas for farming and tourism",
    "They stop rivers from flowing","They prevent settlement everywhere"],"B",
   "Mountain slopes often have fertile soils and attract tourists, so they support farming and tourism."),
 M(C,"Physical Features","Landforms","Easy","Which physical feature is a low-lying area between hills or mountains?",
   ["Plateau","Valley","Mountain","Escarpment"],"B",
   "A valley is the low ground lying between higher land."),
 M(C,"Physical Features","Landforms","Medium","Which physical feature is generally higher than the surrounding land and has a relatively flat top?",
   ["Plateau","Valley","Lake","Swamp"],"A",
   "A plateau is raised land with a fairly flat surface on top."),
 M(C,"Physical Features","Drainage","Easy","Which of the following is a drainage feature?",
   ["Mountain","Plateau","River","Hill"],"C",
   "Drainage features are water features such as rivers, lakes and swamps."),
 M(C,"Agriculture","Water for Farming","Easy","Why are rivers important to farmers?",
   ["They provide water","They destroy all crops","They prevent irrigation","They stop soil formation"],"A",
   "Rivers supply water for crops, animals and irrigation."),
 M(C,"Natural Resources","Water Bodies","Easy","Which activity can be carried out on some lakes and rivers?",
   ["Fishing","Mining mountains","Building hills","Making forests disappear"],"A",
   "Lakes and rivers support fishing, transport and water supply."),

 # ── 21–30  CLIMATE AND VEGETATION ────────────────────────────────────────
 M(C,"Climate","Meaning of Climate","Medium","What is climate?",
   ["The condition of the atmosphere at a particular moment",
    "The average weather conditions of an area over a long period",
    "The amount of soil in an area","The shape of the land"],"B",
   "Weather is what happens on one day; climate is the average over many years."),
 M(C,"Climate","Weather Instruments","Easy","Which instrument is used to measure rainfall?",
   ["Thermometer","Rain gauge","Wind vane","Barometer"],"B",
   "A rain gauge collects rain so the amount can be measured."),
 M(C,"Climate","Weather Instruments","Easy","Which instrument measures temperature?",
   ["Thermometer","Rain gauge","Wind vane","Compass"],"A",
   "A thermometer measures how hot or cold the air is."),
 M(C,"Climate","Factors Affecting Climate","Medium","Which factor is likely to affect the amount of rainfall received in an area?",
   ["Relief","Number of cars","Number of shops","Type of clothing"],"A",
   "Relief matters because air forced to rise over highlands cools and drops rain."),
 M(C,"Agriculture","Rainfall and Farming","Easy","Why is rainfall important to farmers?",
   ["It provides water for crops","It removes all fertile soil",
    "It prevents seed germination","It destroys every crop"],"A",
   "Crops need water, and most Ugandan farming depends on rainfall."),
 M(C,"Vegetation","Meaning of Vegetation","Easy","What is vegetation?",
   ["Animals found in an area","Plants growing naturally in an area",
    "People living in an area","Buildings in an area"],"B",
   "Vegetation means the plant cover growing naturally in an area."),
 M(C,"Vegetation","Human Impact","Easy","Which human activity can destroy natural vegetation?",
   ["Afforestation","Tree planting","Deforestation","Conservation"],"C",
   "Deforestation removes trees and destroys the natural plant cover."),
 M(C,"Environment","Conservation","Easy","Which practice helps conserve forests?",
   ["Bush burning","Afforestation","Excessive logging","Overgrazing"],"B",
   "Afforestation means planting trees, which restores and protects forest cover."),
 M(C,"Environment","Importance of Forests","Medium","Why are forests important?",
   ["They help protect the environment","They prevent all rainfall",
    "They increase soil erosion","They destroy wildlife"],"A",
   "Forests hold soil, attract rain, give timber and shelter wildlife."),
 M(C,"Environment","Deforestation","Easy","What is deforestation?",
   ["Planting trees","Cutting down trees on a large scale",
    "Protecting forests","Growing crops in gardens"],"B",
   "Deforestation is the large-scale clearing of trees."),

 # ── 31–45  SOILS, AGRICULTURE, NATURAL RESOURCES ─────────────────────────
 M(C,"Soils","Soil Types","Medium","Which soil type is generally suitable for growing many crops because it contains a mixture of soil particles?",
   ["Loam soil","Gravel","Rock","Pure sand"],"A",
   "Loam mixes sand, silt and clay, so it holds both water and plant food."),
 M(C,"Soils","Soil Conservation","Medium","Which farming practice helps reduce soil erosion on sloping land?",
   ["Contour farming","Bush burning","Deforestation","Overgrazing"],"A",
   "Ploughing along the contour slows water running down the slope."),
 M(C,"Soils","Soil Erosion","Easy","What is soil erosion?",
   ["Formation of new soil","Removal of the top fertile layer of soil",
    "Planting trees","Addition of manure to soil"],"B",
   "Soil erosion is the wearing away of the fertile top layer by water or wind."),
 M(C,"Soils","Causes of Erosion","Easy","Which of the following can cause soil erosion?",
   ["Planting grass","Deforestation","Mulching","Terracing"],"B",
   "Removing trees leaves soil bare, so rain washes it away."),
 M(C,"Soils","Soil Conservation","Medium","What is terracing mainly used for?",
   ["Controlling soil erosion on slopes","Increasing deforestation",
    "Destroying crops","Increasing flooding"],"A",
   "Terraces are steps cut across a slope that slow running water."),
 M(C,"Agriculture","Farming Practices","Easy","Which agricultural practice involves covering the soil with plant materials?",
   ["Mulching","Mining","Fishing","Weeding"],"A",
   "Mulching covers soil with dry grass or leaves."),
 M(C,"Agriculture","Farming Practices","Medium","One advantage of mulching is that it:",
   ["Increases soil moisture conservation","Removes all nutrients",
    "Causes severe erosion","Destroys soil organisms"],"A",
   "A mulch cover reduces evaporation, so the soil stays moist for longer."),
 M(C,"Agriculture","Cash Crops","Easy","Which of the following is a cash crop commonly grown in Uganda?",
   ["Coffee","Grass","Wild flowers","Bamboo only"],"A",
   "Coffee is one of Uganda's leading cash crops."),
 M(C,"Agriculture","Food Crops","Easy","Which of the following is mainly a food crop?",
   ["Coffee","Tea","Cassava","Cotton"],"C",
   "Cassava is grown mainly to be eaten; coffee, tea and cotton are cash crops."),
 M(C,"Agriculture","Importance of Agriculture","Medium","Why is agriculture important to Uganda?",
   ["It provides food and employment","It prevents trade",
    "It stops industries from operating","It eliminates transport"],"A",
   "Most Ugandans depend on farming for food, income and jobs."),
 M(C,"Agriculture","Livestock","Easy","Which activity involves keeping animals for products such as milk and meat?",
   ["Livestock farming","Forestry","Fishing","Mining"],"A",
   "Livestock farming is the rearing of animals such as cattle and goats."),
 M(C,"Agriculture","Livestock Products","Medium","Which livestock product is used to make leather?",
   ["Milk","Hides and skins","Honey","Eggs"],"B",
   "Hides and skins are tanned to make leather."),
 M(C,"Natural Resources","Fishing","Easy","Which activity involves catching fish from lakes and rivers?",
   ["Forestry","Fishing","Mining","Trading"],"B",
   "Fishing is the catching of fish from water bodies."),
 M(C,"Environment","Fish Conservation","Medium","Which practice can help conserve fish stocks?",
   ["Using illegal fishing methods","Observing fishing regulations",
    "Catching immature fish","Fishing with poison"],"B",
   "Rules on net sizes and closed seasons let young fish grow and breed."),
 M(C,"Natural Resources","Minerals","Easy","Which of the following is a mineral resource?",
   ["Copper","Maize","Cotton","Coffee"],"A",
   "Copper is a mineral dug from the ground; the others are crops."),

 # ── 46–55  POPULATION AND SETTLEMENT ─────────────────────────────────────
 M(C,"Population","Meaning of Population","Easy","What is population?",
   ["The number of people living in an area","The number of animals in a forest",
    "The amount of rainfall received","The size of a lake"],"A",
   "Population means the number of people living in a place."),
 M(C,"Population","Census","Easy","What is a population census?",
   ["Counting livestock only","An official counting of people in a country",
    "Counting buildings only","Measuring rainfall"],"B",
   "A census is the official counting of all people in a country."),
 M(C,"Population","Census","Medium","Why does a government carry out a population census?",
   ["To obtain information for planning","To stop people from farming",
    "To close schools","To prevent development"],"A",
   "Census figures show how many schools, hospitals and roads are needed."),
 M(C,"Population","Social Services","Easy","Which of the following is a social service?",
   ["Education","Fishing","Mining","Hunting"],"A",
   "Education, health and water supply are social services provided to people."),
 M(C,"Population","Population Growth","Medium","One possible disadvantage of a rapidly increasing population is:",
   ["Increased pressure on social services","Automatic increase in forests",
    "Reduced need for schools","Reduced demand for food"],"A",
   "More people need more schools, hospitals and housing than are available."),
 M(C,"Population","Migration","Easy","What is migration?",
   ["Movement of people from one place to another","Movement of clouds",
    "Movement of rivers","Growth of crops"],"A",
   "Migration is the movement of people from one place to settle in another."),
 M(C,"Population","Migration","Easy","A person who moves from one country to another to live there is called a:",
   ["Tourist","Migrant","Farmer","Miner"],"B",
   "A migrant is a person who moves to live in another place or country."),
 M(C,"Population","Causes of Migration","Medium","Which factor may cause people to migrate?",
   ["Search for employment","Availability of nothing to do",
    "Desire to avoid all services","Lack of movement"],"A",
   "People often move to where they can find work and a better living."),
 M(C,"Settlement","Urbanisation","Medium","What is urbanisation?",
   ["Growth and expansion of towns and cities","Movement from towns to forests only",
    "Growth of villages into forests","Destruction of all towns"],"A",
   "Urbanisation is the growth of towns and cities as more people settle in them."),
 M(C,"Settlement","Settlement Types","Medium","Which settlement is more likely to have many industries and large commercial centres?",
   ["Urban settlement","Isolated settlement","Temporary camp","Small homestead"],"A",
   "Towns and cities concentrate industries, shops and services."),

 # ── 56–62  TRANSPORT AND COMMUNICATION ───────────────────────────────────
 M(C,"Transport","Road Transport","Medium","Which means of transport is most suitable for moving bulky goods over long distances by land?",
   ["Road transport","Walking","Bicycle only","Human porterage"],"A",
   "Lorries on roads can carry heavy loads far inland."),
 M(C,"Transport","Rail Transport","Easy","Which transport uses railway lines?",
   ["Rail transport","Water transport","Air transport","Road transport"],"A",
   "Trains run on railway lines."),
 M(C,"Transport","Air Transport","Easy","Which means of transport is generally the fastest for long-distance international travel?",
   ["Bicycle","Air transport","Walking","Canoe"],"B",
   "Aircraft cover long distances far faster than any land or water transport."),
 M(C,"Transport","Water Transport","Medium","What is one advantage of water transport?",
   ["It can carry bulky goods","It requires no water",
    "It can travel on mountains","It is always faster than aircraft"],"A",
   "Ships and ferries carry heavy, bulky cargo cheaply."),
 M(C,"Communication","Modern Communication","Easy","Which means of communication can send information electronically over long distances?",
   ["Telephone","Drum only","Messenger walking","Smoke signal only"],"A",
   "A telephone carries messages electronically over long distances."),
 M(C,"Communication","Mass Media","Easy","Which of the following is an example of mass communication?",
   ["Radio","Personal conversation","Whispering","Private letter only"],"A",
   "Radio reaches very many people at the same time."),
 M(C,"Communication","Importance","Medium","Why is communication important in economic development?",
   ["It helps people exchange information","It prevents business",
    "It stops transport","It destroys markets"],"A",
   "Traders, farmers and government need information to make good decisions."),

 # ── 63–70  TRADE AND INDUSTRY ────────────────────────────────────────────
 M(C,"Trade","Meaning of Trade","Easy","What is trade?",
   ["Buying and selling goods and services","Growing crops only",
    "Building roads only","Teaching in schools only"],"A",
   "Trade is the exchange of goods and services, usually for money."),
 M(C,"Trade","Types of Trade","Easy","Trade carried out within a country is called:",
   ["Internal trade","External trade","International trade","Foreign trade"],"A",
   "Internal trade takes place inside the borders of one country."),
 M(C,"Trade","Types of Trade","Easy","Trade between two or more countries is called:",
   ["Local trade","International trade","Village trade","Internal trade"],"B",
   "International trade crosses national borders."),
 M(C,"Trade","Exports","Easy","What is an export?",
   ["A good brought into a country","A good sent out of a country for sale",
    "A good destroyed in a country","A product stored at home"],"B",
   "Exports are goods sold to other countries."),
 M(C,"Trade","Imports","Easy","What is an import?",
   ["A good brought into a country for sale or use","A good sent out of a country",
    "A crop grown at home","A locally made product only"],"A",
   "Imports are goods bought from other countries."),
 M(C,"Trade","Uganda's Exports","Easy","Which of the following can Uganda export?",
   ["Coffee","Snow","Icebergs","Cars made in every country"],"A",
   "Coffee is one of Uganda's main export earners."),
 M(C,"Industry","Importance of Industry","Medium","Why is industry important?",
   ["It processes raw materials into useful products","It prevents employment",
    "It destroys all raw materials","It stops trade"],"A",
   "Industries add value to raw materials and create jobs."),
 M(C,"Industry","Types of Industry","Easy","Which industry processes cotton into products such as cloth?",
   ["Textile industry","Fishing industry","Mining industry","Tourism industry"],"A",
   "Textile industries spin and weave cotton into cloth."),

 # ── 71–80  EAST AFRICA ───────────────────────────────────────────────────
 M(C,"East Africa","East African Community","Easy","Which of the following is a member of the East African Community?",
   ["Uganda","Ghana","Nigeria","Egypt"],"A",
   "Uganda is a member state of the East African Community."),
 M(C,"East Africa","East African Community","Easy","Which country is found to the east of Uganda and is a member of the East African Community?",
   ["Kenya","Ghana","Zambia","Nigeria"],"A",
   "Kenya lies east of Uganda and is an EAC member."),
 M(C,"East Africa","Regional Cooperation","Medium","What is one major purpose of regional cooperation in East Africa?",
   ["To promote cooperation among member states","To prevent trade",
    "To stop movement of all goods","To increase conflicts"],"A",
   "Regional bodies exist so neighbouring states can work together for shared benefit."),
 M(C,"East Africa","Regional Cooperation","Medium","Which activity can strengthen cooperation among East African countries?",
   ["Regional trade","Closing all borders permanently",
    "Preventing communication","Stopping transport"],"A",
   "Trading together builds shared interests and stronger ties."),
 M(C,"East Africa","Shared Resources","Easy","Which lake is shared by Uganda, Kenya and Tanzania?",
   ["Lake Victoria","Lake Albert","Lake Edward","Lake Kyoga"],"A",
   "Lake Victoria borders all three countries."),
 M(C,"East Africa","Physical Features","Easy","Which East African country is famous for Mount Kilimanjaro?",
   ["Tanzania","Uganda","Rwanda","Burundi"],"A",
   "Mount Kilimanjaro, Africa's highest mountain, is in Tanzania."),
 M(C,"East Africa","Capital Cities","Easy","Which country has Kigali as its capital?",
   ["Rwanda","Kenya","Tanzania","Uganda"],"A",
   "Kigali is the capital city of Rwanda."),
 M(C,"East Africa","Capital Cities","Easy","What is the capital city of Kenya?",
   ["Mombasa","Nairobi","Kisumu","Nakuru"],"B",
   "Nairobi is Kenya's capital and largest city."),
 M(C,"East Africa","Capital Cities","Medium","What is the capital city of Tanzania?",
   ["Arusha","Dodoma","Mwanza","Dar es Salaam"],"B",
   "Dodoma is the official capital of Tanzania, although Dar es Salaam is the largest city."),
 M(C,"East Africa","Shared Resources","Medium","Why is Lake Victoria important to East African countries?",
   ["It supports fishing, transport and other economic activities",
    "It prevents all agriculture","It contains no resources",
    "It separates Africa from Europe"],"A",
   "The lake provides fish, water and a transport route for three countries."),

 # ── 81–90  GOVERNMENT, CITIZENSHIP, LEADERSHIP ───────────────────────────
 M(C,"Citizenship","Meaning of Citizenship","Easy","Who is a citizen?",
   ["A legally recognised member of a country","Any tourist visiting a country",
    "Any animal living in a country","A foreign object"],"A",
   "A citizen is a legally recognised member of a country with rights and duties."),
 M(C,"Citizenship","Responsibilities","Easy","Which is a responsibility of a good citizen?",
   ["Obeying lawful rules","Destroying public property",
    "Avoiding taxes completely","Encouraging violence"],"A",
   "Good citizens obey the law and protect public property."),
 M(C,"Citizenship","Children's Rights","Easy","Which of the following is a right of a child?",
   ["Right to education","Right to destroy property",
    "Right to steal","Right to harm others"],"A",
   "Every child has a right to education."),
 M(C,"Citizenship","Rule of Law","Medium","Why should citizens obey laws?",
   ["To promote order and peaceful living","To create confusion",
    "To encourage crime","To stop development"],"A",
   "Laws keep order so people can live and work together peacefully."),
 M(C,"Government","Democracy","Medium","What is democracy?",
   ["A system in which people participate in choosing their leaders",
    "Rule by animals","Government without laws","Government by force only"],"A",
   "In a democracy, the people choose their leaders and take part in decisions."),
 M(C,"Government","Elections","Easy","What is an election?",
   ["A process of choosing leaders","A process of building a road",
    "A process of planting crops","A process of measuring rainfall"],"A",
   "An election is how citizens choose their leaders by voting."),
 M(C,"Government","Elections","Medium","Why are elections important?",
   ["They allow citizens to choose representatives","They prevent leadership",
    "They stop citizens from participating","They eliminate laws"],"A",
   "Elections give citizens a say in who governs them."),
 M(C,"Government","Arms of Government","Easy","Which arm of government makes laws?",
   ["Legislature","Judiciary","Executive","Police only"],"A",
   "The Legislature, or Parliament, debates and passes laws."),
 M(C,"Government","Arms of Government","Easy","Which arm of government interprets laws?",
   ["Judiciary","Legislature","Executive","Local market"],"A",
   "Courts under the Judiciary interpret and apply the law."),
 M(C,"Government","Arms of Government","Easy","Which arm of government implements laws and government policies?",
   ["Executive","Judiciary","Legislature","Parliament alone"],"A",
   "The Executive carries out the laws and runs the day-to-day work of government."),

 # ── 91–100  UGANDA'S HISTORY ─────────────────────────────────────────────
 M(C,"Uganda's History","Missionaries","Medium","Who were missionaries?",
   ["People who travelled to spread their religion and provide related services",
    "People who came only to trade gold","People who came only to hunt",
    "People who built every railway in Africa"],"A",
   "Missionaries came to spread their faith and also started schools and health centres."),
 M(C,"Uganda's History","Arab Traders","Medium","Which group played an important role in spreading Islam in East Africa?",
   ["Arab traders","European farmers only","Railway workers only","Modern tourists"],"A",
   "Arab traders reaching the coast and interior spread Islam alongside their trade."),
 M(C,"Uganda's History","Explorers","Medium","Why did some European explorers travel through Africa?",
   ["To explore and obtain geographical information","To build modern airports",
    "To conduct modern elections","To establish supermarkets"],"A",
   "Explorers mapped rivers, lakes and land and reported back to Europe."),
 M(C,"Colonialism","Colonial Powers","Easy","Which European country colonised Uganda?",
   ["Britain","France","Germany","Portugal"],"A",
   "Uganda was a British protectorate until independence."),
 M(C,"Colonialism","Aims of Colonialism","Medium","What was one major aim of colonial powers in Africa?",
   ["To control territories and their resources","To give all Africans political power",
    "To eliminate trade","To stop agriculture"],"A",
   "Colonial powers wanted land, raw materials and markets."),
 M(C,"Independence","Meaning of Independence","Easy","What does independence mean?",
   ["Freedom of a country to govern itself","Rule by another country",
    "Loss of sovereignty","Absence of government"],"A",
   "Independence is when a country governs itself instead of being ruled by another."),
 M(C,"Independence","Uganda's Independence","Easy","Uganda gained independence from Britain in:",
   ["1950","1962","1975","1986"],"B",
   "Uganda became independent on 9th October 1962."),
 M(C,"Independence","Uganda's Independence","Medium","Who became Uganda's first Prime Minister at independence?",
   ["Apollo Milton Obote","Idi Amin","Yoweri Museveni","Edward Mutesa II"],"A",
   "Apollo Milton Obote was Prime Minister when Uganda became independent in 1962."),
 M(C,"Independence","Importance of Independence","Medium","Why is Uganda's independence important?",
   ["It gave Uganda self-government","It ended all economic activities",
    "It stopped education","It abolished all leadership"],"A",
   "Independence meant Ugandans could govern themselves and make their own laws."),
 M(C,"Citizenship","National Unity","Medium","Which of the following best promotes national unity?",
   ["Respecting people from different communities","Promoting tribal hatred",
    "Encouraging violence","Discriminating against citizens"],"A",
   "Treating all communities with respect binds a nation together."),
]

for _q in Q:
    _q["origin"] = ORIGIN

assert len(Q) == 100, f"expected 100 questions, got {len(Q)}"

# This batch takes IDs P7_SST_001-100, so it is placed before the earlier P7 set.
EXTRA_FIRST = {"P7": Q}
EXTRA = {}
