#!/usr/bin/env python3
"""
batch4_p7sst.py — second batch of owner-supplied P.7 SST practice questions.

ORIGIN NOTE
    Original revision questions based on the Ugandan P.7 SST curriculum and
    UNEB-style assessment. NOT UNEB past-paper questions, and never labelled
    as such. The genuine past papers live separately in data/papers/.

Submitted as "201-300". Owner questions 101-200 were never supplied, so this
batch is stored in the next free contiguous slot; the builder assigns the IDs.
"""
from qhelpers import M

C = "P7"
ORIGIN = "Original practice question (not a UNEB past paper)"

Q = [
 # ── 201–220  MAP WORK, DIRECTION AND SCALE ───────────────────────────────
 M(C,"Map Work","Direction","Easy","A learner is facing east. In which direction will the learner's left hand point?",
   ["North","South","West","East"],"A",
   "Facing east, north is on your left and south is on your right."),
 M(C,"Map Work","Direction","Easy","A learner is facing south. In which direction will the learner's right hand point?",
   ["East","West","North","South"],"B",
   "Facing south, west is on your right and east is on your left."),
 M(C,"Map Work","Direction","Medium","A village is located north of a school. In which direction is the school from the village?",
   ["North","South","East","West"],"B",
   "Directions work both ways: if the village is north of the school, the school is south of the village."),
 M(C,"Map Work","Direction","Medium","A hospital is west of a market. Where is the market in relation to the hospital?",
   ["East","West","North","South"],"A",
   "If the hospital is west of the market, then the market must be east of the hospital."),
 M(C,"Map Work","Instruments","Easy","Which instrument would a learner use to determine the direction of a place in the field?",
   ["Compass","Thermometer","Rain gauge","Measuring cylinder"],"A",
   "A compass needle points north, so it is used to find direction."),
 M(C,"Map Work","Scale","Medium","Why is a map scale important?",
   ["It helps the user determine actual distances","It shows the colour of the map",
    "It identifies all animals","It measures temperature"],"A",
   "A scale tells you what a distance on the map stands for on the ground."),
 M(C,"Map Work","Map Features","Easy","Which of the following is a human-made feature?",
   ["Road","Mountain","River","Lake"],"A",
   "Roads are built by people; mountains, rivers and lakes occur naturally."),
 M(C,"Map Work","Map Features","Easy","Which of the following is a physical feature?",
   ["Railway","Road","River","School"],"C",
   "A river is a natural feature; railways, roads and schools are made by people."),
 M(C,"Map Work","Map Interpretation","Medium","A map shows a railway line connecting two towns. What does the railway line help the map reader understand?",
   ["The route followed by railway transport","The amount of rainfall",
    "The population of the towns","The type of soil"],"A",
   "A railway symbol shows the route trains follow between places."),
 M(C,"Map Work","Map Key","Easy","Why should a learner study the key before using a map?",
   ["To understand the symbols used on the map","To know the weather",
    "To calculate population","To identify the map paper"],"A",
   "The key explains what each symbol on the map stands for."),
 M(C,"Map Work","Map Symbols","Easy","Which of the following is normally shown using a symbol on a map?",
   ["School","Temperature","Age of a person","Height of a learner"],"A",
   "Features such as schools, churches and bridges are drawn as symbols."),
 M(C,"Map Work","Map Interpretation","Medium","If two places are very close together on a map, what can this suggest?",
   ["They may be close together on the ground","They are always in different countries",
    "One must be a mountain","They must have different climates"],"A",
   "Distance on a map stands for real distance, so places drawn close together are usually near each other."),
 M(C,"Map Work","Direction","Easy","Which direction is directly opposite to east?",
   ["North","South","West","North-east"],"C",
   "East and west are opposite each other on the compass."),
 M(C,"Map Work","Direction","Easy","Which direction is directly opposite to north?",
   ["South","East","West","North-west"],"A",
   "North and south are opposite each other on the compass."),
 M(C,"Map Work","Direction","Easy","Which of the following is an intermediate direction?",
   ["North","South","North-east","West"],"C",
   "Intermediate directions lie between the cardinal points, such as north-east."),
 M(C,"Map Work","Direction","Medium","A farmer's garden is south-east of his home. In which direction should the farmer walk to reach the garden?",
   ["South-east","North-west","North-east","South-west"],"A",
   "To reach a place lying south-east of you, you walk towards the south-east."),
 M(C,"Map Work","Map Features","Medium","What does a map boundary normally show?",
   ["The limit of an area","The amount of rainfall",
    "The height of a mountain","The age of a town"],"A",
   "A boundary line marks where one area ends and another begins."),
 M(C,"Map Work","Uses of Maps","Easy","Why are maps useful to travellers?",
   ["They help travellers locate places and plan routes","They provide food",
    "They measure body temperature","They replace vehicles"],"A",
   "A map shows where places are and how to get from one to another."),
 M(C,"Map Work","Types of Maps","Medium","Which type of map is mainly used to show relief and physical features?",
   ["Physical map","Political speech","Population register","Weather report"],"A",
   "A physical map shows landforms such as mountains, valleys, rivers and lakes."),
 M(C,"Map Work","Grid References","Medium","A learner wants to find the location of a town on a map. Which information would be most useful?",
   ["Grid reference","Shoe size","Rainfall record only","Crop yield"],"A",
   "A grid reference uses numbered lines to give the exact position of a place."),

 # ── 221–240  CLIMATE, WEATHER AND VEGETATION ─────────────────────────────
 M(C,"Climate","Weather and Climate","Medium","What is weather?",
   ["The condition of the atmosphere at a particular place and time",
    "The average condition of an area over many years",
    "The type of soil in an area","The population of an area"],"A",
   "Weather is what the atmosphere is doing right now; climate is the long-term average."),
 M(C,"Climate","Weather Instruments","Easy","Which instrument measures temperature?",
   ["Thermometer","Rain gauge","Wind vane","Compass"],"A",
   "A thermometer measures how hot or cold the air is."),
 M(C,"Climate","Weather Instruments","Easy","Which instrument measures rainfall?",
   ["Rain gauge","Thermometer","Wind vane","Compass"],"A",
   "A rain gauge collects rain so the amount can be measured."),
 M(C,"Climate","Weather Instruments","Easy","Which instrument shows the direction from which wind is blowing?",
   ["Wind vane","Rain gauge","Thermometer","Ruler"],"A",
   "A wind vane turns until it points towards where the wind is coming from."),
 M(C,"Climate","Weather and Farming","Easy","Why is weather information important to farmers?",
   ["It helps them plan farming activities","It prevents farming",
    "It destroys crops","It stops rainfall"],"A",
   "Knowing the forecast helps farmers decide when to plant, weed, spray or harvest."),
 M(C,"Climate","Weather and Farming","Medium","A farmer hears that heavy rainfall is expected. Which activity might the farmer postpone?",
   ["Burning dry vegetation","Harvesting crops","Planting trees","Protecting soil"],"B",
   "Harvested crops need dry weather, so harvesting is delayed until the rain passes."),
 M(C,"Climate","Weather and Farming","Easy","Which condition is most suitable for drying harvested crops?",
   ["Sunny and dry weather","Continuous heavy rainfall","Flooding","Very wet conditions"],"A",
   "Sunshine and dry air remove moisture so crops can be stored without rotting."),
 M(C,"Climate","Factors Affecting Climate","Medium","Which factor can influence the climate of an area?",
   ["Altitude","Number of shops","Number of schools","Type of clothing"],"A",
   "Altitude, distance from water and relief all affect the climate of a place."),
 M(C,"Climate","Altitude and Temperature","Hard","Why do highland areas often have cooler temperatures?",
   ["Temperature generally decreases with increasing altitude",
    "They are always closer to the equator","They receive no sunlight","They have no vegetation"],"A",
   "Air gets thinner and cooler as you go higher, so highlands are colder than lowlands."),
 M(C,"Vegetation","Vegetation and Rainfall","Medium","Which natural vegetation is associated with areas receiving enough rainfall?",
   ["Forest","Desert only","Bare rock","Sand dunes"],"A",
   "Plenty of rainfall supports thick tree growth, so forests develop."),
 M(C,"Vegetation","Human Impact","Easy","Which human activity threatens natural vegetation?",
   ["Deforestation","Afforestation","Conservation","Reforestation"],"A",
   "Deforestation removes trees and destroys the natural plant cover."),
 M(C,"Environment","Afforestation","Easy","What is afforestation?",
   ["Planting trees to establish forests","Cutting down trees",
    "Burning forests","Removing vegetation"],"A",
   "Afforestation means planting trees where there was no forest before."),
 M(C,"Environment","Trees and Soil","Medium","Why should trees be planted around farms?",
   ["They can help protect soil and the environment","They always reduce rainfall",
    "They destroy all crops","They prevent soil formation"],"A",
   "Tree roots hold the soil, and trees give shade and act as windbreaks."),
 M(C,"Environment","Burning and the Air","Hard","Which gas is released when large amounts of vegetation are burned?",
   ["Carbon dioxide","Oxygen only","Hydrogen only","Nitrogen only"],"A",
   "Burning plant material releases carbon dioxide into the air."),
 M(C,"Environment","Conservation","Easy","Which practice can help reduce environmental damage caused by cutting trees?",
   ["Replanting trees","Cutting more trees","Burning forests","Removing seedlings"],"A",
   "Replanting restores the tree cover that was lost."),
 M(C,"Vegetation","Wildlife Habitats","Easy","Why is vegetation important to wildlife?",
   ["It provides food and shelter","It prevents animals from living",
    "It destroys habitats","It removes all water"],"A",
   "Plants feed many animals and give them places to hide and nest."),
 M(C,"Soils","Causes of Erosion","Medium","Which activity is likely to increase soil erosion?",
   ["Removing vegetation from steep slopes","Planting grass","Terracing","Mulching"],"A",
   "Bare steep ground lets rainwater run fast and wash the soil away."),
 M(C,"Vegetation","Vegetation Types","Medium","Which vegetation type is commonly associated with areas having moderate rainfall and long grass?",
   ["Grassland","Desert","Mangrove forest only","Alpine snow"],"A",
   "Moderate rainfall supports grassland with tall grass and scattered trees."),
 M(C,"Environment","Bush Burning","Medium","Why should people avoid unnecessary bush burning?",
   ["It can destroy vegetation and soil organisms","It increases forest cover",
    "It always improves soil","It increases wildlife habitats"],"A",
   "Fire kills plants and the small living things in the soil that keep it fertile."),
 M(C,"Environment","Conservation","Easy","Which practice is an example of environmental conservation?",
   ["Protecting forests","Dumping waste in rivers","Poaching","Wetland destruction"],"A",
   "Conservation means protecting natural resources so they last."),

 # ── 241–260  SOILS, AGRICULTURE AND LAND USE ─────────────────────────────
 M(C,"Soils","Soil Profile","Medium","Which part of the soil contains most of the organic matter useful to plants?",
   ["Topsoil","Bedrock","Solid rock","Gravel only"],"A",
   "Topsoil is the dark upper layer rich in decayed plant and animal matter."),
 M(C,"Soils","Soil Fertility","Easy","Why is topsoil important?",
   ["It contains nutrients needed by many plants","It contains no nutrients",
    "It prevents plant growth","It is always made of rocks"],"A",
   "Topsoil holds the plant food and moisture that crops need."),
 M(C,"Soils","Soil Conservation","Easy","Which farming practice helps control soil erosion on steep slopes?",
   ["Terracing","Deforestation","Overgrazing","Bush burning"],"A",
   "Terraces are steps cut across a slope that slow water running downhill."),
 M(C,"Agriculture","Contour Farming","Medium","What is contour farming?",
   ["Ploughing or planting along the contours of a slope","Planting only in swamps",
    "Farming without soil","Farming only on flat roofs"],"A",
   "Working across the slope instead of up and down it stops water racing downhill."),
 M(C,"Agriculture","Moisture Conservation","Easy","Which farming practice helps conserve moisture in the soil?",
   ["Mulching","Burning crop residues","Deforestation","Overgrazing"],"A",
   "A mulch of dry grass or leaves reduces evaporation from the soil."),
 M(C,"Agriculture","Crop Rotation","Hard","Why do farmers practise crop rotation?",
   ["To help maintain soil fertility and reduce some pests and diseases",
    "To destroy all crops","To prevent harvesting","To increase soil erosion"],"A",
   "Different crops use different nutrients, and changing them breaks pest cycles."),
 M(C,"Agriculture","Manure","Easy","Which material can be used as organic manure?",
   ["Animal droppings","Plastic bottles","Glass","Metal"],"A",
   "Animal droppings rot down and return plant food to the soil."),
 M(C,"Soils","Land Use","Medium","Why should farmers avoid cultivating very steep slopes without conservation measures?",
   ["They are highly prone to soil erosion","They cannot receive sunlight",
    "They always have no soil","They cannot support any plants"],"A",
   "Water runs fast down steep ground and carries the soil with it."),
 M(C,"Agriculture","Farming Systems","Medium","Which farming system involves moving animals from one grazing area to another?",
   ["Pastoralism","Plantation farming","Fishing","Irrigation"],"A",
   "Pastoralists move their herds in search of pasture and water."),
 M(C,"Agriculture","Irrigation","Easy","What is irrigation?",
   ["Supplying water to crops artificially","Removing crops from farms",
    "Destroying soil","Cutting trees"],"A",
   "Irrigation brings water to crops through channels, pipes or sprinklers."),
 M(C,"Agriculture","Irrigation","Medium","Why is irrigation useful?",
   ["It supplies crops with water when rainfall is insufficient","It prevents crop growth",
    "It removes nutrients","It causes drought"],"A",
   "Irrigation lets farming continue in dry seasons and dry areas."),
 M(C,"Agriculture","Food Crops","Easy","Which crop is commonly used as a source of food in Uganda?",
   ["Cassava","Coffee","Tea","Cotton"],"A",
   "Cassava is a staple food crop; coffee, tea and cotton are grown for sale."),
 M(C,"Agriculture","Cash Crops","Medium","Which crop is an important source of foreign exchange for Uganda?",
   ["Coffee","Grass","Wild plants","Weeds"],"A",
   "Coffee exports earn Uganda a large share of its foreign currency."),
 M(C,"Agriculture","Poultry","Easy","Why do farmers keep poultry?",
   ["For products such as eggs and meat","To produce petrol",
    "To produce copper","To produce cement"],"A",
   "Poultry such as hens supply eggs and meat, and can be sold for income."),
 M(C,"Agriculture","Livestock Products","Easy","Which livestock product is used in making shoes and bags?",
   ["Leather","Milk","Eggs","Honey"],"A",
   "Leather is made from tanned hides and skins."),
 M(C,"Agriculture","Mixed Farming","Easy","What is mixed farming?",
   ["Growing crops and keeping livestock on the same farm","Growing only one crop",
    "Keeping only fish","Farming without animals or crops"],"A",
   "Mixed farming combines crops and animals so each supports the other."),
 M(C,"Agriculture","Beekeeping","Easy","Which agricultural activity involves keeping bees?",
   ["Beekeeping","Fishing","Forestry","Mining"],"A",
   "Beekeeping, or apiculture, is the rearing of bees in hives."),
 M(C,"Agriculture","Beekeeping","Easy","Which product is obtained from bees?",
   ["Honey","Leather","Cotton","Coffee"],"A",
   "Bees produce honey, and also beeswax."),
 M(C,"Environment","Land Use","Hard","Why should agricultural land be used carefully?",
   ["To maintain its productivity for future generations","To destroy soil fertility",
    "To increase erosion","To prevent food production"],"A",
   "Careless use exhausts the soil, leaving less for those who come after us."),
 M(C,"Soils","Soil Fertility","Medium","Which practice is most likely to improve soil fertility?",
   ["Applying suitable manure","Removing all vegetation",
    "Continuous burning","Overgrazing"],"A",
   "Manure adds nutrients and improves the structure of the soil."),

 # ── 261–280  POPULATION, SETTLEMENT, TRANSPORT, COMMUNICATION ────────────
 M(C,"Settlement","Factors for Settlement","Medium","Why do many people settle in areas with fertile soils?",
   ["They can support agriculture","They have no water",
    "They prevent farming","They have no transport"],"A",
   "Fertile soil grows good crops, so people settle where food can be produced."),
 M(C,"Settlement","Factors for Settlement","Easy","Why are settlements often found near water sources?",
   ["People need water for domestic and economic activities","People do not need water",
    "Water prevents all settlement","Water destroys all crops"],"A",
   "Water is needed for drinking, washing, animals and crops."),
 M(C,"Population","Population Distribution","Medium","Which factor may influence the distribution of population?",
   ["Availability of jobs","Colour of houses only",
    "Type of clothing","Number of televisions"],"A",
   "People gather where there is work, land, water and services."),
 M(C,"Population","Population Density","Medium","What is population density?",
   ["The number of people living per unit area","The total number of houses",
    "The amount of rainfall","The number of schools only"],"A",
   "Density compares the number of people with the size of the land they occupy."),
 M(C,"Population","Population Density","Medium","Which area is likely to have a high population density?",
   ["A town with many jobs and services","An uninhabited forest",
    "A desert with no water","A remote mountain peak"],"A",
   "Towns attract many people because of work, schools and services."),
 M(C,"Population","Migration","Easy","What is rural-urban migration?",
   ["Movement of people from rural areas to urban areas","Movement from cities to villages",
    "Movement between countries only","Movement of animals"],"A",
   "Rural-urban migration is people leaving villages to live in towns."),
 M(C,"Population","Causes of Migration","Easy","Which may attract people from rural areas to towns?",
   ["Employment opportunities","Lack of services","Lack of markets","Lack of schools"],"A",
   "Jobs, schools and better services pull people towards towns."),
 M(C,"Settlement","Urbanisation","Hard","What problem can rapid urbanisation create?",
   ["Pressure on housing and social services","Automatic improvement of all services",
    "Reduced need for housing","Reduced population"],"A",
   "When towns grow faster than their services, housing, water and schools fall short."),
 M(C,"Population","Social Services","Easy","Which is an example of a social service?",
   ["Health care","Mining","Fishing","Trading"],"A",
   "Health care, education and water supply are services provided to people."),
 M(C,"Population","Education","Easy","Why are schools important in a community?",
   ["They provide education and skills","They prevent development",
    "They stop communication","They destroy culture"],"A",
   "Schools give young people the knowledge and skills their community needs."),
 M(C,"Transport","Water Transport","Easy","Which means of transport is most suitable for crossing a lake?",
   ["Water transport","Railway transport","Road transport","Air transport only"],"A",
   "Boats and ferries are the practical way to cross a lake."),
 M(C,"Transport","Air Transport","Easy","Which means of transport is particularly useful for transporting passengers over very long distances quickly?",
   ["Air transport","Bicycle","Walking","Human porterage"],"A",
   "Aircraft cover very long distances in a few hours."),
 M(C,"Transport","Roads and Farming","Medium","Why are roads important to farmers?",
   ["They help farmers transport produce to markets","They prevent farmers from selling produce",
    "They destroy all crops","They prevent trade"],"A",
   "Without a usable road, produce cannot reach buyers in time."),
 M(C,"Transport","Transport Problems","Hard","Which transport problem can make agricultural products spoil before reaching markets?",
   ["Poor roads and delays","Good roads","Efficient transport","Short distances"],"A",
   "Slow journeys on bad roads let perishable produce rot before it is sold."),
 M(C,"Communication","Mass Media","Easy","Which means of communication can reach many people at the same time?",
   ["Radio","Private conversation","Whispering","Personal note"],"A",
   "Radio broadcasts the same message to very many listeners at once."),
 M(C,"Communication","Communication and Trade","Medium","Why is the telephone useful to traders?",
   ["It allows them to communicate quickly with customers and suppliers","It prevents business",
    "It destroys goods","It replaces all transport"],"A",
   "Traders can check prices, place orders and arrange delivery without travelling."),
 M(C,"Communication","Modern Communication","Easy","Which is an example of modern communication?",
   ["Internet","Smoke signals","Drum beating only","Messenger walking"],"A",
   "The internet is a modern electronic means of sending information."),
 M(C,"Communication","Modern Communication","Medium","What is one advantage of the internet?",
   ["It allows information to be shared quickly","It prevents communication",
    "It stops trade","It destroys schools"],"A",
   "Information can be sent around the world in seconds."),
 M(C,"Transport","Transport and Development","Hard","Why is good transport important for national development?",
   ["It connects producers, consumers and markets","It prevents movement",
    "It stops trade","It isolates communities"],"A",
   "Goods, workers and services can only move where transport allows."),
 M(C,"Transport","Rail Transport","Medium","Which means of transport is generally suitable for transporting large quantities of heavy goods over long distances?",
   ["Rail transport","Walking","Bicycle","Human porterage"],"A",
   "Trains carry very heavy, bulky loads cheaply over long land distances."),

 # ── 281–300  GOVERNMENT, HISTORY, CITIZENSHIP, EAST AFRICA ───────────────
 M(C,"Government","Meaning of Government","Easy","What is a government?",
   ["A system or group of people responsible for governing a country",
    "A farming organisation only","A group of traders","A school club"],"A",
   "The government is the body that runs a country and makes decisions for it."),
 M(C,"Government","Need for Government","Medium","Why does a country need government?",
   ["To maintain order and provide leadership","To create confusion",
    "To stop development","To prevent citizens from working"],"A",
   "Government keeps order, makes laws and provides services."),
 M(C,"Government","Responsibilities","Easy","Which of the following is a responsibility of government?",
   ["Providing public services","Destroying schools",
    "Preventing health care","Encouraging lawlessness"],"A",
   "Government provides schools, health care, roads, water and security."),
 M(C,"Leadership","Local Government","Easy","What is a local government?",
   ["Government that administers a local area","Government of another continent",
    "A private company","A family organisation"],"A",
   "Local government runs the affairs of a district, sub-county or village."),
 M(C,"Leadership","Local Government","Medium","Why are local governments important?",
   ["They help provide services to people at local level","They prevent local development",
    "They stop citizens from participating","They replace every national institution"],"A",
   "Decisions made close to the people fit local needs better."),
 M(C,"Leadership","Qualities of a Leader","Easy","Which of the following is a good quality of a leader?",
   ["Honesty","Corruption","Dishonesty","Cruelty"],"A",
   "An honest leader can be trusted with public responsibility."),
 M(C,"Leadership","Accountability","Hard","Why should leaders be accountable?",
   ["They should explain how they use public resources and exercise authority",
    "They should never answer questions","They should avoid citizens",
    "They should hide public resources"],"A",
   "Public money and power belong to the people, so leaders must answer for them."),
 M(C,"Citizenship","Responsibilities","Easy","Which action shows responsible citizenship?",
   ["Protecting public property","Destroying public facilities",
    "Disobeying lawful instructions","Encouraging violence"],"A",
   "Public property belongs to everyone, so citizens should protect it."),
 M(C,"Citizenship","Children's Rights","Easy","Which of the following is a child right?",
   ["Right to protection from abuse","Right to steal",
    "Right to destroy property","Right to harm others"],"A",
   "Every child has the right to be protected from harm and abuse."),
 M(C,"Citizenship","Education","Medium","Why should children attend school?",
   ["To acquire knowledge, skills and values","To avoid learning",
    "To prevent employment in adulthood","To avoid social interaction"],"A",
   "School prepares children for work and for life in their community."),
 M(C,"Colonialism","Meaning of Colonialism","Medium","What is colonialism?",
   ["Control of one country or territory by another power","Democratic self-government",
    "Local farming","Regional trade"],"A",
   "Colonialism is when one country takes control of another and rules it."),
 M(C,"Colonialism","Colonial Powers","Easy","Which country colonised Uganda?",
   ["Britain","France","Portugal","Spain"],"A",
   "Uganda was ruled by Britain as a protectorate until independence in 1962."),
 M(C,"Uganda's History","Missionaries","Medium","Why did missionaries establish schools in some parts of Uganda?",
   ["To provide education and support the spread of their religious teachings",
    "To stop all education","To destroy farming","To prevent communication"],"A",
   "Missionaries taught reading and writing partly so people could read religious books."),
 M(C,"Uganda's History","Traders","Easy","Why did traders come to East Africa?",
   ["To exchange and sell goods","To stop all trade",
    "To destroy markets","To prevent movement"],"A",
   "Traders came seeking goods such as ivory, and brought items to sell in exchange."),
 M(C,"Uganda's History","Spread of Islam","Medium","Which group played an important role in the early spread of Islam along the East African coast?",
   ["Arab and Swahili traders","European tourists","Modern farmers","Railway engineers"],"A",
   "Arab traders settled along the coast and, with the Swahili, spread Islam there."),
 M(C,"East Africa","East African Community","Easy","Which country is a member of the East African Community?",
   ["Uganda","Nigeria","Ghana","Senegal"],"A",
   "Uganda is a member state of the East African Community."),
 M(C,"East Africa","Regional Cooperation","Medium","What is one benefit of the East African Community?",
   ["It promotes cooperation among member states","It prevents regional trade",
    "It stops communication","It increases border conflicts"],"A",
   "Member states work together on trade, transport and other shared concerns."),
 M(C,"East Africa","Peace and Cooperation","Medium","Which of the following can promote peace in East Africa?",
   ["Cooperation among countries","Tribal hatred","Armed conflict","Discrimination"],"A",
   "Countries that work together have fewer reasons to quarrel."),
 M(C,"Trade","Regional Trade","Medium","Why is regional trade important?",
   ["It allows countries to exchange goods and services","It prevents economic growth",
    "It stops markets","It prevents cooperation"],"A",
   "Each country sells what it produces well and buys what it lacks."),
 M(C,"Trade","Types of Trade","Hard","A Ugandan trader buys goods from Kenya and sells them in Uganda. What type of trade is this?",
   ["International trade","Internal trade",
    "Barter within one household","Subsistence farming"],"A",
   "The goods crossed a national border, so this is international trade."),
]

for _q in Q:
    _q["origin"] = ORIGIN

assert len(Q) == 100, f"expected 100 questions, got {len(Q)}"

EXTRA_FIRST = {}
EXTRA = {"P7": Q}          # appended after batch 3, so it takes the next 100 IDs
