#!/usr/bin/env python3
"""
batch6_p7sst.py — fourth batch of owner-supplied P.7 SST practice questions.

ORIGIN NOTE
    Original UNEB-style revision questions based on the Ugandan P.7 SST
    curriculum. NOT UNEB past-paper questions, and never labelled as such.

Submitted as "401-500". The builder assigns the real IDs, continuing the owner
block; anything that exactly repeats an earlier question is reported and not
served twice.
"""
from qhelpers import M

C = "P7"
ORIGIN = "Original practice question (not a UNEB past paper)"

Q = [
 # ── 401–420  ENVIRONMENT AND CONSERVATION ────────────────────────────────
 M(C,"Environment","Deforestation","Easy","Which activity is most likely to cause deforestation?",
   ["Cutting down trees without replacing them","Planting trees",
    "Establishing tree plantations","Protecting forests"],"A",
   "Deforestation happens when trees are cleared and nothing is replanted."),
 M(C,"Environment","Forest Conservation","Medium","Why should forests be conserved?",
   ["They provide habitats and help protect the environment","They prevent all rainfall",
    "They have no economic value","They prevent farming everywhere"],"A",
   "Forests shelter wildlife, hold soil, and influence rainfall and climate."),
 M(C,"Soils","Causes of Erosion","Easy","Which activity can cause soil erosion?",
   ["Removing vegetation from land","Planting grass","Terracing","Mulching"],"A",
   "Bare soil has nothing to hold it, so rain and wind carry it away."),
 M(C,"Soils","Soil Conservation","Medium","A farmer plants grass on a bare slope. What problem is the farmer mainly trying to control?",
   ["Soil erosion","Population growth","Air pollution","Overfishing"],"A",
   "Grass roots bind the soil and slow water running down the slope."),
 M(C,"Soils","Soil Conservation","Easy","Which practice helps prevent soil erosion?",
   ["Terracing","Deforestation","Overgrazing","Bush burning"],"A",
   "Terraces are steps cut across a slope that slow running water."),
 M(C,"Soils","Soil Erosion","Easy","What is soil erosion?",
   ["Removal of the top layer of soil by agents such as water or wind",
    "Addition of manure to soil","Planting crops","Formation of rocks"],"A",
   "Erosion is the wearing away and carrying off of the fertile topsoil."),
 M(C,"Soils","Agents of Erosion","Medium","Which agent commonly causes soil erosion in Uganda?",
   ["Running water","Schools","Roads","Houses"],"A",
   "Rainwater running over the surface is the main cause of erosion in Uganda."),
 M(C,"Environment","Water Pollution","Easy","Which activity can cause water pollution?",
   ["Dumping waste into rivers","Protecting wetlands","Treating sewage","Planting trees"],"A",
   "Waste thrown into a river makes the water unsafe for people and fish."),
 M(C,"Environment","Water Conservation","Medium","Why should water sources be protected?",
   ["To provide safe water for people and other organisms","To prevent people from drinking water",
    "To increase pollution","To destroy aquatic life"],"A",
   "Clean, protected sources give safe water and keep aquatic life alive."),
 M(C,"Environment","Air Pollution","Medium","Which activity can reduce air pollution?",
   ["Planting trees","Burning plastics","Burning forests","Burning waste in open spaces"],"A",
   "Trees take in carbon dioxide and help clean the air."),
 M(C,"Environment","Wildlife Conservation","Medium","What is wildlife conservation?",
   ["Protection and proper management of wild animals and their habitats",
    "Hunting all wild animals","Destroying forests","Selling all wildlife"],"A",
   "Conservation means protecting animals and the places where they live."),
 M(C,"Environment","Poaching","Easy","What is poaching?",
   ["Illegal hunting or capturing of wildlife","Protecting wildlife",
    "Breeding domestic animals","Planting trees"],"A",
   "Poaching is hunting or trapping wild animals against the law."),
 M(C,"Environment","Poaching","Medium","Why is poaching dangerous to wildlife?",
   ["It can reduce animal populations","It increases wildlife populations",
    "It protects habitats","It improves breeding"],"A",
   "Killing animals faster than they breed drives their numbers down."),
 M(C,"Environment","Protected Areas","Easy","Which area is established mainly to protect wildlife?",
   ["National park","Industrial area","Market","Residential area"],"A",
   "National parks are set aside to protect animals and their habitats."),
 M(C,"Geography","Tourism","Medium","Why are national parks important to Uganda?",
   ["They help conserve wildlife and promote tourism","They encourage poaching",
    "They destroy habitats","They prevent tourism"],"A",
   "Parks keep wildlife safe and attract tourists who bring income."),
 M(C,"Environment","Wetlands","Easy","Which activity can destroy wetlands?",
   ["Filling wetlands for construction","Protecting wetlands",
    "Controlling pollution","Restoring wetlands"],"A",
   "Filling a wetland with soil to build on it destroys it permanently."),
 M(C,"Environment","Wetlands","Medium","Why are wetlands important?",
   ["They help regulate water and provide habitats","They are useless areas",
    "They increase pollution","They prevent all plant growth"],"A",
   "Wetlands store water, reduce floods and shelter many plants and animals."),
 M(C,"Environment","Conservation","Easy","Which practice is an example of conservation?",
   ["Replanting trees after harvesting","Cutting all trees",
    "Dumping waste in rivers","Hunting endangered animals"],"A",
   "Replacing what you take keeps the resource available in future."),
 M(C,"Natural Resources","Renewable Resources","Medium","Which of the following is a renewable resource?",
   ["Trees","Copper","Gold","Petroleum"],"A",
   "Trees can grow again if replanted; minerals and oil cannot be replaced."),
 M(C,"Environment","Sustainable Use","Hard","Why should natural resources be used wisely?",
   ["To ensure they benefit both present and future generations","To destroy them quickly",
    "To prevent economic activities","To increase environmental degradation"],"A",
   "Using resources carefully means there is still something left for those who come after us."),

 # ── 421–440  CLIMATE, WEATHER AND DISASTERS ──────────────────────────────
 M(C,"Climate","Weather Instruments","Easy","Which instrument measures rainfall?",
   ["Rain gauge","Thermometer","Compass","Wind vane"],"A",
   "A rain gauge collects rain so the amount can be measured."),
 M(C,"Climate","Weather Instruments","Easy","Which instrument measures temperature?",
   ["Thermometer","Rain gauge","Compass","Wind vane"],"A",
   "A thermometer measures how hot or cold the air is."),
 M(C,"Climate","Weather Instruments","Easy","Which instrument shows wind direction?",
   ["Wind vane","Thermometer","Rain gauge","Barometer"],"A",
   "A wind vane points towards where the wind is coming from."),
 M(C,"Climate","Weather and Farming","Easy","Why is weather forecasting useful to farmers?",
   ["It helps farmers plan activities","It prevents farmers from planting",
    "It stops rainfall","It destroys crops"],"A",
   "A forecast tells farmers when to plant, spray or harvest."),
 M(C,"Climate","Weather and Farming","Easy","Which weather condition is most suitable for harvesting mature crops?",
   ["Dry weather","Heavy rainfall","Flooding","Continuous storms"],"A",
   "Dry weather lets harvested crops be gathered and stored without rotting."),
 M(C,"Climate","Weather and Climate","Medium","What is climate?",
   ["The average weather conditions of a place over a long period",
    "Weather at one particular moment","The shape of the land","The number of people in an area"],"A",
   "Climate is the pattern of weather averaged over many years."),
 M(C,"Climate","Factors Affecting Climate","Medium","Which factor affects the climate of a place?",
   ["Altitude","Number of shops","Number of vehicles only","Type of school"],"A",
   "Altitude, distance from large water bodies and relief all shape climate."),
 M(C,"Climate","Altitude and Temperature","Hard","Why are highland areas generally cooler than lowland areas?",
   ["Temperature decreases with increasing altitude","They receive no sunlight",
    "They have no vegetation","They are always covered by water"],"A",
   "Air becomes thinner and colder the higher you go."),
 M(C,"Environment","Floods","Easy","Which condition may lead to flooding?",
   ["Very heavy rainfall","Long dry periods","Low population","Tree planting"],"A",
   "When rain falls faster than the ground can absorb it, water floods the land."),
 M(C,"Environment","Floods","Medium","Which human activity can increase flooding?",
   ["Blocking drainage channels with rubbish","Maintaining drainage systems",
    "Protecting wetlands","Planting vegetation"],"A",
   "Blocked drains cannot carry water away, so it spreads over the land."),
 M(C,"Environment","Disaster Preparedness","Medium","What should people do during a flood warning?",
   ["Move to a safer place when advised","Move toward flooded rivers",
    "Play in flood water","Block drainage channels"],"A",
   "Moving to higher, safer ground early protects lives."),
 M(C,"Environment","Health and Environment","Medium","Which disease can increase when stagnant water provides breeding places for mosquitoes?",
   ["Malaria","Broken bones","Tooth decay","Blindness"],"A",
   "Mosquitoes breed in still water and spread malaria."),
 M(C,"Environment","Health and Environment","Easy","Which practice can help reduce mosquito breeding around homes?",
   ["Removing stagnant water","Storing water in open containers",
    "Blocking drainage","Throwing rubbish into drains"],"A",
   "Clearing still water removes the places where mosquitoes lay eggs."),
 M(C,"Climate","Drought","Easy","What is drought?",
   ["A long period of unusually low rainfall","A period of heavy rainfall",
    "A type of soil","A type of vegetation"],"A",
   "A drought is a long spell with far less rain than usual."),
 M(C,"Climate","Drought","Medium","Which activity may become difficult during severe drought?",
   ["Crop farming","Road construction only","Map reading","School registration"],"A",
   "Without rain, crops wilt and harvests fail."),
 M(C,"Agriculture","Drought Management","Hard","Which practice can help farmers cope with drought?",
   ["Water harvesting","Destroying water sources",
    "Removing all vegetation","Wasting water"],"A",
   "Collecting and storing rainwater provides a supply for the dry season."),
 M(C,"Environment","Natural Disasters","Medium","What is a natural disaster?",
   ["A destructive event caused by natural processes","A school examination",
    "A market day","A normal farming activity"],"A",
   "Floods, droughts, earthquakes and landslides are natural disasters."),
 M(C,"Environment","Natural Hazards","Easy","Which of the following is a natural hazard?",
   ["Landslide","Shopping","Trading","Teaching"],"A",
   "A landslide is a sudden movement of soil and rock down a slope."),
 M(C,"Environment","Landslides","Hard","Why can landslides occur on steep slopes?",
   ["Heavy rainfall can saturate and weaken the soil","Roads always prevent them",
    "Trees always cause them","Flat land causes all landslides"],"A",
   "Waterlogged soil becomes heavy and loses grip, so it slides downhill."),
 M(C,"Environment","Landslides","Medium","Which activity can help reduce the risk of landslides?",
   ["Maintaining vegetation on slopes","Removing all trees",
    "Cultivating dangerously steep slopes without protection","Destroying terraces"],"A",
   "Plant roots hold the soil together and reduce the chance of a slide."),

 # ── 441–460  ECONOMIC ACTIVITIES ─────────────────────────────────────────
 M(C,"Natural Resources","Fishing","Easy","Which economic activity involves catching fish?",
   ["Fishing","Forestry","Mining","Tourism"],"A",
   "Fishing is the catching of fish from lakes, rivers and seas."),
 M(C,"Natural Resources","Mining","Easy","Which economic activity involves extracting minerals from the ground?",
   ["Mining","Fishing","Farming","Tourism"],"A",
   "Mining takes minerals such as copper and gold out of the ground."),
 M(C,"Agriculture","Economic Activities","Easy","Which economic activity involves growing crops?",
   ["Agriculture","Mining","Transport","Banking"],"A",
   "Agriculture is the growing of crops and rearing of animals."),
 M(C,"Trade","Economic Activities","Easy","Which activity involves buying and selling goods?",
   ["Trade","Forestry","Fishing","Mining"],"A",
   "Trade is the exchange of goods and services, usually for money."),
 M(C,"Geography","Tourism","Medium","Why is tourism important to Uganda?",
   ["It can provide employment and foreign exchange","It destroys all national parks",
    "It prevents economic development","It stops international visitors"],"A",
   "Tourists create jobs and spend foreign currency in the country."),
 M(C,"Geography","Tourism","Easy","Which attraction can bring tourists to Uganda?",
   ["Wildlife","Polluted rivers","Destroyed forests","Poor roads only"],"A",
   "Uganda's gorillas, game parks and scenery draw visitors."),
 M(C,"Geography","Tourism","Easy","Which national resource can support the tourism industry?",
   ["Wildlife","Plastic waste","Polluted water","Destroyed vegetation"],"A",
   "Wildlife is one of Uganda's biggest tourist attractions."),
 M(C,"Geography","Tourism","Medium","Why should tourist attractions be protected?",
   ["To maintain tourism and conserve resources","To prevent tourists from visiting",
    "To destroy wildlife","To reduce employment"],"A",
   "If attractions are damaged, tourists stop coming and the income is lost."),
 M(C,"Industry","Manufacturing","Easy","Which activity involves producing goods in factories?",
   ["Manufacturing","Fishing","Farming","Tourism"],"A",
   "Manufacturing is making goods on a large scale in factories."),
 M(C,"Industry","Manufacturing","Medium","Why is manufacturing important?",
   ["It adds value to raw materials","It prevents production",
    "It stops trade","It destroys all employment"],"A",
   "A processed product sells for more than the raw material it came from."),
 M(C,"Industry","Processing","Medium","A factory changes cotton into cloth. What has happened?",
   ["Raw material has been processed into a finished product",
    "A physical feature has been formed","A crop has been planted","A river has been created"],"A",
   "Processing turns a raw material into something ready to use."),
 M(C,"Industry","Types of Industry","Easy","Which industry uses cotton as a major raw material?",
   ["Textile industry","Dairy industry","Mining industry","Fishing industry"],"A",
   "Textile mills spin and weave cotton into cloth."),
 M(C,"Industry","Types of Industry","Easy","Which industry uses milk as a major raw material?",
   ["Dairy industry","Textile industry","Timber industry","Mining industry"],"A",
   "The dairy industry processes milk into butter, cheese and yoghurt."),
 M(C,"Industry","Energy and Industry","Easy","Why do factories require electricity?",
   ["To operate machines and equipment","To stop production",
    "To prevent manufacturing","To destroy raw materials"],"A",
   "Machines in a factory need power to run."),
 M(C,"Natural Resources","Hydro-electric Power","Medium","Which source can generate hydroelectric power?",
   ["Moving water","Cotton","Coffee","Timber"],"A",
   "Falling or fast-flowing water turns turbines that generate electricity."),
 M(C,"Industry","Energy and Development","Medium","Why is electricity important for development?",
   ["It supports industries, homes and services","It prevents economic activities",
    "It stops communication","It prevents production"],"A",
   "Factories, hospitals, schools and homes all depend on power."),
 M(C,"Trade","Producers and Consumers","Easy","Which person buys goods for personal use?",
   ["Consumer","Producer","Manufacturer","Wholesaler only"],"A",
   "A consumer is the person who finally uses the goods."),
 M(C,"Trade","Producers and Consumers","Easy","Which person or organisation makes goods?",
   ["Producer","Consumer","Tourist","Passenger"],"A",
   "A producer grows or manufactures the goods that others buy."),
 M(C,"Trade","Markets","Easy","Why do traders need markets?",
   ["Markets provide places where goods can be bought and sold","Markets prevent trade",
    "Markets destroy goods","Markets prevent customers"],"A",
   "A market brings buyers and sellers together in one place."),
 M(C,"Agriculture","Rural Employment","Medium","Which activity can provide employment in rural Uganda?",
   ["Agriculture","Space exploration","Deep-sea shipping","Aircraft manufacturing only"],"A",
   "Most rural Ugandans earn their living from farming."),

 # ── 461–480  HISTORY AND CULTURE ─────────────────────────────────────────
 M(C,"Uganda's History","Importance of History","Medium","Why is history important?",
   ["It helps people understand events of the past","It prevents learning",
    "It destroys culture","It stops development"],"A",
   "Understanding the past helps explain the present and guide the future."),
 M(C,"Culture","Meaning of Culture","Easy","What is culture?",
   ["The way of life of a group of people","The size of a country",
    "The number of roads","The amount of rainfall"],"A",
   "Culture is a people's way of life: language, dress, food, beliefs and customs."),
 M(C,"Culture","Cultural Heritage","Easy","Which is an example of cultural heritage?",
   ["Traditional dances","Modern traffic lights","Mobile phones","Factory machines"],"A",
   "Traditional dances, songs and crafts are passed down as heritage."),
 M(C,"Culture","Cultural Heritage","Medium","Why should cultural heritage be preserved?",
   ["To pass knowledge and traditions to future generations","To destroy identity",
    "To stop learning","To prevent unity"],"A",
   "Heritage gives a people their identity and links them to their ancestors."),
 M(C,"Culture","Oral Tradition","Easy","Which of the following is an example of oral tradition?",
   ["Storytelling","Printed newspaper","Television news","Written constitution"],"A",
   "Oral tradition is knowledge passed on by word of mouth."),
 M(C,"Culture","Oral Tradition","Medium","Why was oral tradition important in traditional societies?",
   ["It helped pass knowledge from one generation to another","It prevented communication",
    "It destroyed history","It replaced farming"],"A",
   "Before writing was common, stories and songs carried a people's history."),
 M(C,"Uganda's History","Missionaries","Easy","Which group played an important role in the spread of Christianity in many parts of Uganda?",
   ["Christian missionaries","Modern tourists","Railway passengers","Fishermen"],"A",
   "Missionaries came to teach their faith and founded churches and schools."),
 M(C,"Uganda's History","Missionaries","Medium","Why did missionaries establish schools?",
   ["To provide education alongside their missionary work","To prevent education",
    "To destroy reading","To stop communication"],"A",
   "Reading was needed for religious study, so missionaries taught it in schools."),
 M(C,"Colonialism","Colonial Powers","Easy","Which European country colonised Uganda?",
   ["Britain","France","Belgium","Germany"],"A",
   "Uganda was a British protectorate until independence."),
 M(C,"Independence","Uganda's Independence","Easy","Uganda became independent in:",
   ["1962","1957","1971","1986"],"A",
   "Uganda became independent on 9th October 1962."),
 M(C,"Independence","Meaning of Independence","Easy","What does independence mean?",
   ["Freedom from foreign political control","Rule by another country",
    "Loss of sovereignty","Absence of government"],"A",
   "An independent country is free to govern itself."),
 M(C,"Independence","African Nationalism","Medium","Why did African nationalists demand independence?",
   ["To achieve self-government","To strengthen colonial rule",
    "To prevent Africans from governing themselves","To stop development"],"A",
   "Nationalists wanted Africans, not foreigners, to rule their own countries."),
 M(C,"Uganda's History","Sources of History","Medium","Which of the following is a source of historical information?",
   ["Oral tradition","Future prediction","Guesswork only","Rumour only"],"A",
   "Oral tradition, documents and artefacts are all sources of history."),
 M(C,"Uganda's History","Sources of History","Medium","Which source can provide written information about the past?",
   ["Historical documents","Weather forecast","Modern advertisement","Traffic light"],"A",
   "Letters, records and books written in the past are historical documents."),
 M(C,"Uganda's History","Sources of History","Hard","Why should historical information be checked carefully?",
   ["Some information may be inaccurate or biased","All historical information is automatically correct",
    "History never changes","Sources are never different"],"A",
   "Different sources may disagree, so a historian compares them before believing one."),
 M(C,"Uganda's History","Colonial Transport","Medium","Which activity helped connect inland Uganda to the coast during colonial times?",
   ["Railway transport","Air transport","Modern highways","Mobile phones"],"A",
   "The Uganda Railway linked the interior to the coast at Mombasa."),
 M(C,"Colonialism","Colonial Transport","Medium","Why was transport important during the colonial period?",
   ["It facilitated movement of people and goods","It stopped all trade",
    "It prevented administration","It destroyed communication"],"A",
   "Colonial rule depended on moving officials, soldiers and goods."),
 M(C,"Settlement","Growth of Towns","Medium","Which historical activity contributed to the growth of towns?",
   ["Trade","Isolation","Lack of roads","Lack of markets"],"A",
   "Places where people came to buy and sell grew into towns."),
 M(C,"Settlement","Growth of Towns","Hard","Why did some early settlements grow near trading centres?",
   ["Trade created opportunities for exchange and employment",
    "Trading centres had no economic activity","People avoided markets",
    "Transport was impossible"],"A",
   "Where goods change hands there is work, income and reason to settle."),
 M(C,"Citizenship","Patriotism","Medium","Which value can be learned from studying the history of Uganda?",
   ["Patriotism","Hatred","Discrimination","Dishonesty"],"A",
   "Learning what the country has been through builds love and pride for it."),

 # ── 481–500  GOVERNMENT, CITIZENSHIP AND EAST AFRICA ─────────────────────
 M(C,"Citizenship","Meaning of Citizenship","Easy","What is citizenship?",
   ["The legal membership of a person in a country","Visiting a country for one day",
    "Trading in a market","Living in a hotel"],"A",
   "Citizenship is legal membership of a country, with rights and duties."),
 M(C,"Citizenship","Responsibilities","Easy","Which is a responsibility of a good citizen?",
   ["Obeying lawful laws","Destroying public property",
    "Encouraging violence","Stealing public resources"],"A",
   "Good citizens obey the law and respect what belongs to everyone."),
 M(C,"Citizenship","Public Property","Medium","Why should citizens protect public property?",
   ["Public property belongs to the community and supports public services",
    "It has no value","It belongs to criminals","It should always be destroyed"],"A",
   "Schools, boreholes and roads are paid for by everyone and serve everyone."),
 M(C,"Citizenship","Peace","Easy","Which action promotes peace in a community?",
   ["Respecting other people's rights","Encouraging violence",
    "Spreading hatred","Destroying property"],"A",
   "When people respect one another's rights, quarrels are fewer."),
 M(C,"Citizenship","Tolerance","Medium","Why is tolerance important?",
   ["It helps people live peacefully despite their differences","It encourages conflict",
    "It prevents cooperation","It causes discrimination"],"A",
   "Tolerance lets people of different tribes, faiths and views live together."),
 M(C,"Citizenship","Human Rights","Medium","What is a human right?",
   ["A basic freedom or entitlement belonging to a person","A punishment",
    "A tax","A type of crop"],"A",
   "Human rights belong to every person simply because they are human."),
 M(C,"Citizenship","Human Rights","Easy","Which is an example of a human right?",
   ["Right to life","Right to steal","Right to destroy property","Right to abuse others"],"A",
   "The right to life is the most basic human right."),
 M(C,"Citizenship","Child Protection","Medium","Why should children be protected from abuse?",
   ["To ensure their safety and development","To prevent education",
    "To encourage violence","To deny their rights"],"A",
   "Children can only grow and learn well when they are safe."),
 M(C,"Government","Purpose of Laws","Medium","What is the main purpose of laws?",
   ["To guide behaviour and maintain order","To encourage disorder",
    "To stop justice","To prevent peaceful living"],"A",
   "Laws set the rules that let people live together peacefully."),
 M(C,"Government","Judiciary","Easy","Which institution interprets laws in Uganda?",
   ["Courts of law","Markets","Schools","Banks"],"A",
   "Courts under the Judiciary interpret and apply the law."),
 M(C,"Government","Parliament","Easy","Which institution makes laws for the country?",
   ["Parliament","Hospital","Bank","Police station"],"A",
   "Parliament debates and passes the laws of Uganda."),
 M(C,"Government","Parliament","Medium","Why is Parliament important?",
   ["It represents citizens and makes laws","It grows crops",
    "It treats patients","It operates airports"],"A",
   "Members of Parliament speak for the people who elected them and make laws."),
 M(C,"Government","Judiciary","Medium","What is the role of the judiciary?",
   ["Administering justice","Growing crops","Selling goods","Building roads"],"A",
   "The Judiciary settles disputes and decides cases fairly."),
 M(C,"East Africa","East African Community","Medium","What is the East African Community?",
   ["A regional organisation promoting cooperation among East African countries",
    "A school club","A Ugandan political party","A farming cooperative"],"A",
   "The EAC brings neighbouring states together to work on shared interests."),
 M(C,"East Africa","East African Community","Easy","Which country is a member of the East African Community?",
   ["Uganda","Nigeria","Ghana","Morocco"],"A",
   "Uganda is a member state of the East African Community."),
 M(C,"East Africa","Regional Cooperation","Medium","Which of the following can result from regional cooperation?",
   ["Increased trade","Increased isolation","Reduced communication","Permanent conflict"],"A",
   "Working together opens wider markets and easier movement of goods."),
 M(C,"East Africa","Peace and Cooperation","Medium","Why is peace important for East African countries?",
   ["It creates an environment for development and cooperation","It prevents trade",
    "It destroys businesses","It prevents movement"],"A",
   "Investment, trade and schooling all need a peaceful setting."),
 M(C,"East Africa","Cultural Exchange","Medium","Which activity can strengthen relationships between East African countries?",
   ["Cultural exchange","Conflict","Discrimination","Border violence"],"A",
   "Sharing music, sport and language builds understanding between neighbours."),
 M(C,"East Africa","Regional Integration","Hard","Why is regional integration important?",
   ["It can promote trade, cooperation and development",
    "It prevents countries from cooperating","It stops regional communication",
    "It eliminates trade"],"A",
   "Joining together gives member states a bigger market and a stronger voice."),
 M(C,"East Africa","Cultural Exchange","Medium","A Ugandan learner visits Kenya to learn about its culture and history. Which activity is taking place?",
   ["Cultural exchange","Soil erosion","Industrialisation","Deforestation"],"A",
   "Visiting another country to learn its ways of life is cultural exchange."),
]

for _q in Q:
    _q["origin"] = ORIGIN

assert len(Q) == 100, f"expected 100 questions, got {len(Q)}"

EXTRA_FIRST = {}
EXTRA = {"P7": Q}
