#!/usr/bin/env python3
"""
batch5_p7sst.py — third batch of owner-supplied P.7 SST practice questions.

ORIGIN NOTE
    Original UNEB-style revision questions based on the Ugandan P.7 SST
    curriculum. NOT UNEB past-paper questions, and never labelled as such.

Submitted as "301-400". The builder assigns the actual IDs, continuing the
owner block; anything that exactly repeats an earlier question is reported
and not served twice.

TRANSCRIPTION NOTE
    Q360 ("Why should population growth be properly planned?") arrived with no
    "Correct answer" line. Option A is the only defensible answer, so A is used
    and the gap is flagged rather than guessed at silently.
"""
from qhelpers import M

C = "P7"
ORIGIN = "Original practice question (not a UNEB past paper)"

Q = [
 # ── 301–320  MAP WORK AND PHYSICAL FEATURES ──────────────────────────────
 M(C,"Map Work","Map Key","Easy","A learner wants to locate a school on a map. Which part of the map should the learner first check to understand the symbols?",
   ["Key","Title only","Border","Scale only"],"A",
   "The key explains what every symbol on the map stands for."),
 M(C,"Map Work","Direction","Medium","A village is located south-west of a health centre. In which direction should a person travel from the village to reach the health centre?",
   ["North-east","South-east","North-west","South-west"],"A",
   "If the village is south-west of the health centre, the health centre lies north-east of the village."),
 M(C,"Map Work","Map Interpretation","Easy","A road on a map connects two towns. What does this suggest?",
   ["The road provides a route between the towns","The towns are mountains",
    "The road is a river","The towns are forests"],"A",
   "A road symbol joining two places shows the route travellers can follow."),
 M(C,"Map Work","Map Symbols","Medium","Which feature would most likely be shown as a line on a map?",
   ["River","School","Mountain peak","Market building"],"A",
   "Long, narrow features such as rivers, roads and railways are drawn as lines."),
 M(C,"Map Work","Map Symbols","Medium","Why are symbols used instead of drawing every feature exactly as it appears on the ground?",
   ["To make maps simple and easy to read","To make maps confusing",
    "To remove important information","To prevent people from using maps"],"A",
   "Symbols keep a map clear and small enough to be useful."),
 M(C,"Physical Features","Waterfalls","Easy","Which physical feature is formed when water flows over a steep drop in a river?",
   ["Waterfall","Valley","Plateau","Hill"],"A",
   "A waterfall forms where a river drops suddenly over hard rock."),
 M(C,"Physical Features","Landforms","Easy","Which physical feature is usually found between hills or mountains?",
   ["Valley","Lake","Plateau","Desert"],"A",
   "A valley is the low ground lying between higher land."),
 M(C,"Physical Features","Landforms","Easy","Which physical feature has a relatively flat top and is higher than the surrounding land?",
   ["Plateau","Valley","Swamp","River"],"A",
   "A plateau is raised land with a fairly level surface."),
 M(C,"Natural Resources","Lakes","Easy","Which activity is commonly carried out on Lake Victoria?",
   ["Fishing","Mountain climbing","Cattle grazing","Gold smelting"],"A",
   "Lake Victoria supports a large fishing industry."),
 M(C,"Physical Features","Rivers","Easy","Why are rivers important to communities?",
   ["They provide water for different activities","They prevent settlement everywhere",
    "They destroy all crops","They prevent transport"],"A",
   "Rivers supply water for homes, animals, crops and industry."),
 M(C,"Physical Features","Mountains","Easy","Which mountain is found in eastern Uganda?",
   ["Mount Elgon","Rwenzori Mountains","Mount Stanley","Mount Speke"],"A",
   "Mount Elgon stands in eastern Uganda on the border with Kenya."),
 M(C,"Physical Features","Mountains","Easy","The Rwenzori Mountains are mainly found in:",
   ["Western Uganda","Eastern Uganda","Northern Uganda","Central Uganda"],"A",
   "The Rwenzori range lies in western Uganda along the D.R. Congo border."),
 M(C,"Geography","Tourism","Medium","Why do some tourists visit the Rwenzori Mountains?",
   ["For mountain scenery and climbing","To buy fish",
    "To grow cotton","To operate railway trains"],"A",
   "The snow-capped peaks and scenery attract climbers and sightseers."),
 M(C,"East Africa","Shared Resources","Easy","Which lake is shared by Uganda, Kenya and Tanzania?",
   ["Lake Victoria","Lake Albert","Lake Edward","Lake Kyoga"],"A",
   "Lake Victoria borders all three countries."),
 M(C,"Physical Features","Rivers","Easy","Which river flows northwards from Lake Victoria through Uganda?",
   ["River Nile","River Kagera","River Katonga","River Semliki"],"A",
   "The Nile leaves Lake Victoria at Jinja and flows north."),
 M(C,"Natural Resources","Hydro-electric Power","Medium","Which physical feature can provide water for hydroelectric power generation?",
   ["River","Desert","Hill","Plateau"],"A",
   "Falling river water turns turbines to generate electricity."),
 M(C,"Environment","Wetlands","Medium","Why are wetlands important to the environment?",
   ["They help store and regulate water","They prevent all plant growth",
    "They increase soil erosion","They have no environmental value"],"A",
   "Wetlands soak up water in wet seasons and release it slowly in dry ones."),
 M(C,"Environment","Wetlands","Medium","Which activity can destroy wetlands?",
   ["Draining them for settlement","Protecting them",
    "Planting suitable vegetation","Controlling pollution"],"A",
   "Draining a wetland to build on it removes it permanently."),
 M(C,"Geography","Tourism","Medium","Which physical feature is most suitable for providing a natural site for a mountain tourist attraction?",
   ["Mountain","Swamp","Flat road","Market"],"A",
   "Mountains offer scenery, climbing and cool highland air that attract tourists."),
 M(C,"Environment","Conservation","Hard","Why should physical features be conserved?",
   ["They provide environmental and economic benefits","They are useless",
    "They prevent tourism","They stop all economic activities"],"A",
   "Features such as lakes, forests and mountains support life and earn income."),

 # ── 321–340  AGRICULTURE AND NATURAL RESOURCES ───────────────────────────
 M(C,"Agriculture","Soil Conservation","Medium","A farmer plants crops along the contour lines of a steep slope. Which problem is the farmer mainly trying to reduce?",
   ["Soil erosion","Drought","Pest infestation","Low population"],"A",
   "Planting across the slope slows water so it cannot wash the soil away."),
 M(C,"Agriculture","Farming Practices","Easy","A farmer covers the soil around crops with dry grass. What farming practice is being used?",
   ["Mulching","Irrigation","Terracing","Crop rotation"],"A",
   "Covering soil with dry plant material is called mulching."),
 M(C,"Agriculture","Mulching","Easy","Which is a major benefit of mulching?",
   ["Conserving soil moisture","Increasing soil erosion",
    "Removing nutrients","Destroying crops"],"A",
   "A mulch reduces evaporation so the soil stays moist longer."),
 M(C,"Agriculture","Crop Rotation","Medium","A farmer grows maize this season and beans on the same land during another planned season. Which practice is this?",
   ["Crop rotation","Deforestation","Overgrazing","Bush burning"],"A",
   "Changing the crop grown on the same land each season is crop rotation."),
 M(C,"Agriculture","Crop Rotation","Medium","Why can crop rotation be useful?",
   ["It helps maintain soil fertility and manage some pests","It always destroys soil",
    "It prevents crops from growing","It increases erosion"],"A",
   "Different crops use different nutrients, and changing them breaks pest cycles."),
 M(C,"Agriculture","Irrigation","Easy","Which farming practice involves supplying crops with water artificially?",
   ["Irrigation","Mulching","Terracing","Weeding"],"A",
   "Irrigation brings water to crops through channels, pipes or sprinklers."),
 M(C,"Agriculture","Cash Crops","Easy","Which crop is an important cash crop in Uganda?",
   ["Coffee","Cassava","Beans","Sweet potatoes"],"A",
   "Coffee is grown mainly for sale and export."),
 M(C,"Trade","Cash Crops and Income","Medium","Why are cash crops important to Uganda?",
   ["They can earn income and foreign exchange","They cannot be sold",
    "They prevent trade","They provide no economic benefit"],"A",
   "Selling cash crops abroad brings foreign currency into the country."),
 M(C,"Agriculture","Food Crops","Easy","Which of the following is mainly grown as a food crop?",
   ["Beans","Coffee","Tea","Cotton"],"A",
   "Beans are grown mainly to be eaten; the others are cash crops."),
 M(C,"Agriculture","Livestock Products","Easy","Which livestock product is used to make leather?",
   ["Hides and skins","Milk","Eggs","Honey"],"A",
   "Hides and skins are tanned to produce leather."),
 M(C,"Agriculture","Beekeeping","Easy","Which activity involves keeping bees for useful products?",
   ["Beekeeping","Fishing","Mining","Forestry"],"A",
   "Beekeeping is the rearing of bees in hives."),
 M(C,"Agriculture","Beekeeping","Easy","Which product is commonly obtained from bees?",
   ["Honey","Leather","Cotton","Copper"],"A",
   "Bees produce honey and beeswax."),
 M(C,"Agriculture","Mixed Farming","Easy","A farmer keeps cattle and grows maize on the same farm. What type of farming is this?",
   ["Mixed farming","Fishing","Forestry","Plantation farming"],"A",
   "Mixed farming combines crops and livestock on one farm."),
 M(C,"Soils","Soil Conservation","Medium","Why should farmers conserve soil?",
   ["To maintain soil fertility and agricultural productivity","To increase erosion",
    "To destroy crops","To prevent farming"],"A",
   "Healthy soil keeps producing good harvests season after season."),
 M(C,"Soils","Causes of Erosion","Medium","Which activity can lead to loss of fertile topsoil?",
   ["Deforestation","Terracing","Mulching","Contour farming"],"A",
   "Removing trees leaves soil bare so rain washes the topsoil away."),
 M(C,"Natural Resources","Forest Products","Easy","Which natural resource is obtained from forests?",
   ["Timber","Copper","Petroleum","Salt only"],"A",
   "Trees in forests are cut for timber, poles and firewood."),
 M(C,"Natural Resources","Minerals","Easy","Which natural resource is obtained through mining?",
   ["Copper","Coffee","Maize","Cotton"],"A",
   "Copper is dug from the ground; the others are grown."),
 M(C,"Natural Resources","Conservation","Hard","Why should mineral resources be used carefully?",
   ["Many are non-renewable","They grow every year",
    "They are unlimited","They are agricultural crops"],"A",
   "Once a mineral is mined and used it cannot be replaced."),
 M(C,"Environment","Reforestation","Easy","Which activity can help restore forests?",
   ["Reforestation","Deforestation","Bush burning","Overgrazing"],"A",
   "Reforestation is replanting trees where a forest has been cut."),
 M(C,"Environment","Forests and Farming","Medium","Why are forests important to farmers?",
   ["They can help protect soil and influence the environment","They destroy all farmland",
    "They prevent rainfall","They have no relationship with farming"],"A",
   "Tree roots hold soil, and forests provide shade, windbreaks and moisture."),

 # ── 341–360  POPULATION, SETTLEMENT AND SOCIAL SERVICES ──────────────────
 M(C,"Settlement","Urban Attraction","Medium","A town has many factories, schools, hospitals and shops. What is likely to attract people to the town?",
   ["Employment and services","Lack of services","Lack of markets","Lack of transport"],"A",
   "Jobs and services are the main pull factors that draw people to towns."),
 M(C,"Population","Population Density","Medium","What is population density?",
   ["Number of people per unit area","Number of houses in a country",
    "Number of schools","Amount of rainfall"],"A",
   "Density compares the number of people with the area of land they occupy."),
 M(C,"Population","Population Density","Medium","Which area is likely to have low population density?",
   ["Remote area with few services","Busy city centre",
    "Industrial town","Large commercial centre"],"A",
   "Few people settle where there is little work, water or service provision."),
 M(C,"Settlement","Factors for Settlement","Easy","Which factor can encourage settlement in an area?",
   ["Availability of water","Lack of food","Lack of transport","Lack of security"],"A",
   "People settle where they can get water, food, work and safety."),
 M(C,"Settlement","Factors for Settlement","Easy","Why do many people prefer to settle near fertile land?",
   ["It supports agriculture","It prevents farming","It has no water","It prevents food production"],"A",
   "Fertile land grows good crops, so families can feed themselves and sell surplus."),
 M(C,"Population","Migration","Easy","What is rural-urban migration?",
   ["Movement from rural areas to towns and cities","Movement from cities to villages",
    "Movement between two forests","Movement of animals"],"A",
   "Rural-urban migration is people leaving the countryside for towns."),
 M(C,"Settlement","Urbanisation","Medium","Which is a possible effect of rural-urban migration?",
   ["Pressure on urban housing","Emptying all towns",
    "Decrease in urban population","Elimination of traffic"],"A",
   "More arrivals than housing leads to crowding and slums."),
 M(C,"Population","Social Services","Easy","Which service is provided by hospitals?",
   ["Health care","Banking","Road construction","Mining"],"A",
   "Hospitals treat the sick and provide health care."),
 M(C,"Population","Social Services","Easy","Which service is mainly provided by schools?",
   ["Education","Fishing","Banking","Transport"],"A",
   "Schools provide education and skills."),
 M(C,"Population","Social Services","Easy","Why are health centres important in communities?",
   ["They provide health services","They provide rainfall",
    "They produce crops","They build mountains"],"A",
   "A nearby health centre treats illness before it becomes serious."),
 M(C,"Population","Census","Easy","What is a census?",
   ["An official counting of a country's population","A count of crops",
    "A weather forecast","A map exercise"],"A",
   "A census is the official counting of all people in a country."),
 M(C,"Population","Census","Medium","Why does government need population information?",
   ["For planning and providing services","To prevent development",
    "To stop schools","To prevent health care"],"A",
   "Population figures show how many schools, clinics and roads are needed."),
 M(C,"Population","Population Growth","Hard","Which may result from a very high population increase?",
   ["Greater demand for schools and health services","Less need for food",
    "Less need for housing","Less pressure on land"],"A",
   "More people means more demand for land, food, housing and services."),
 M(C,"Population","Social Services","Easy","Which is an example of a social service?",
   ["Clean water supply","Gold mining","Coffee farming","Fishing"],"A",
   "Water supply, health and education are services provided to the community."),
 M(C,"Population","Health","Easy","Why is clean water important?",
   ["It supports health and domestic activities","It causes disease",
    "It prevents hygiene","It destroys crops"],"A",
   "Safe water prevents disease and is needed for cooking and washing."),
 M(C,"Settlement","Settlement Types","Medium","Which settlement is most likely to have a large number of commercial activities?",
   ["Urban settlement","Isolated homestead","Remote forest","Uninhabited mountain"],"A",
   "Towns concentrate shops, markets and businesses."),
 M(C,"Settlement","Transport and Settlement","Medium","Why do roads influence settlement?",
   ["They improve accessibility and movement","They prevent communication",
    "They stop trade","They destroy all settlements"],"A",
   "People settle where they can travel to markets, schools and work."),
 M(C,"Population","Causes of Migration","Medium","Which factor may cause people to leave an area?",
   ["Lack of employment opportunities","Good schools","Good roads","Good health services"],"A",
   "Push factors such as no work drive people to move away."),
 M(C,"Population","Causes of Migration","Easy","Which factor may attract people to an area?",
   ["Availability of employment","Insecurity","Lack of water","Poor roads"],"A",
   "Pull factors such as jobs attract people into an area."),
 M(C,"Population","Population Planning","Hard","Why should population growth be properly planned?",
   ["To ensure resources and services meet people's needs","To prevent development",
    "To stop settlement","To reduce education"],"A",
   "Planning makes sure schools, clinics, water and land keep pace with the number of people."),

 # ── 361–380  TRANSPORT, COMMUNICATION, TRADE AND INDUSTRY ────────────────
 M(C,"Transport","Transport and Farming","Medium","A farmer has harvested a large quantity of maize and needs to take it to a distant market. Which service is most important?",
   ["Transport","Tourism","Banking only","Broadcasting"],"A",
   "Produce cannot be sold until it can be moved to where buyers are."),
 M(C,"Transport","Rail Transport","Medium","Which transport method is useful for moving bulky goods over long distances?",
   ["Rail transport","Walking","Bicycle","Human porterage"],"A",
   "Trains carry very heavy, bulky loads cheaply over long distances."),
 M(C,"Transport","Air Transport","Medium","Why is air transport useful for urgent goods?",
   ["It is generally fast","It is always the cheapest",
    "It does not require airports","It travels without aircraft"],"A",
   "Aircraft deliver perishable or urgent goods in hours rather than days."),
 M(C,"Transport","Water Transport","Easy","Which means of transport is used on Lake Victoria?",
   ["Water transport","Railway transport","Road transport","Pipeline transport"],"A",
   "Boats and ferries carry people and goods across the lake."),
 M(C,"Trade","Transport Costs","Hard","Which transport problem can increase the price of goods?",
   ["High transport costs","Good roads","Short distances","Efficient transport"],"A",
   "Traders add the cost of moving goods to the selling price."),
 M(C,"Transport","Roads and Trade","Easy","Why are good roads important to traders?",
   ["They make movement of goods easier","They prevent markets",
    "They stop customers","They destroy businesses"],"A",
   "Good roads let goods reach markets quickly and in good condition."),
 M(C,"Communication","Telephone","Easy","Which communication method allows a person to speak directly with another person over a distance?",
   ["Telephone","Poster","Newspaper","Billboard"],"A",
   "A telephone carries the voice directly between two people."),
 M(C,"Communication","Mass Media","Easy","Which is a form of mass communication?",
   ["Television","Private conversation","Personal whisper","One-to-one greeting"],"A",
   "Television reaches very many people at the same time."),
 M(C,"Communication","Communication and Trade","Medium","Why is communication important in business?",
   ["It allows businesses to exchange information","It prevents customers from contacting sellers",
    "It stops trade","It destroys markets"],"A",
   "Buyers and sellers must share prices, orders and delivery details."),
 M(C,"Trade","Types of Trade","Easy","What is internal trade?",
   ["Trade carried out within a country","Trade between continents",
    "Trade between countries only","Trade between planets"],"A",
   "Internal trade takes place inside the borders of one country."),
 M(C,"Trade","Types of Trade","Easy","What is international trade?",
   ["Trade between countries","Trade within one village",
    "Trade within one family","Trade between two farms only"],"A",
   "International trade crosses national borders."),
 M(C,"Trade","Exports","Medium","A Ugandan company sells coffee to another country. What is the coffee called from Uganda's point of view?",
   ["Export","Import","Local product","Consumer good only"],"A",
   "Goods sold out of the country are exports."),
 M(C,"Trade","Imports","Medium","Uganda buys machinery from another country. The machinery is an:",
   ["Import","Export","Local crop","Domestic service"],"A",
   "Goods bought from abroad are imports."),
 M(C,"Trade","Exports","Medium","Why are exports important?",
   ["They can earn foreign exchange","They prevent income",
    "They stop production","They prevent international trade"],"A",
   "Selling abroad brings foreign currency needed to pay for imports."),
 M(C,"Industry","Meaning of Industry","Medium","What is an industry?",
   ["An economic activity involving production or processing of goods and services",
    "A type of weather","A physical feature","A type of settlement only"],"A",
   "An industry produces goods or provides services on a large scale."),
 M(C,"Industry","Processing","Easy","A factory turns cotton into cloth. What type of activity is this?",
   ["Industrial processing","Fishing","Forestry","Mining"],"A",
   "Changing a raw material into a finished product is processing."),
 M(C,"Industry","Importance of Industry","Medium","Why are industries important to a country?",
   ["They create employment and add value to raw materials","They destroy all jobs",
    "They prevent production","They stop trade"],"A",
   "Industries provide jobs and make raw materials more valuable."),
 M(C,"Industry","Types of Industry","Easy","Which industry processes milk into products such as yoghurt?",
   ["Dairy industry","Textile industry","Mining industry","Timber industry"],"A",
   "The dairy industry processes milk into butter, cheese and yoghurt."),
 M(C,"Industry","Industry and Transport","Medium","Why do industries need transport?",
   ["To move raw materials and finished products","To prevent production",
    "To stop trade","To prevent workers from reaching factories"],"A",
   "Factories must bring materials in and send products out."),
 M(C,"Trade","Banking","Easy","Which service helps traders safely keep and transfer money?",
   ["Banking","Fishing","Forestry","Tourism"],"A",
   "Banks keep money safe and move it between people and businesses."),

 # ── 381–400  GOVERNMENT, CITIZENSHIP, HISTORY, EAST AFRICA ───────────────
 M(C,"Government","Democracy","Medium","What is democracy?",
   ["A system in which people participate in choosing their leaders","Rule without laws",
    "Rule by force only","Government without citizens"],"A",
   "In a democracy the people choose their leaders and share in decisions."),
 M(C,"Government","Elections","Easy","Why are elections important in a democracy?",
   ["They allow citizens to choose leaders","They prevent citizens from participating",
    "They eliminate leadership","They prevent laws"],"A",
   "Elections give citizens a say in who governs them."),
 M(C,"Leadership","Qualities of a Leader","Easy","Which quality should a good leader have?",
   ["Honesty","Corruption","Dishonesty","Tribal hatred"],"A",
   "An honest leader can be trusted with public responsibility."),
 M(C,"Leadership","Accountability","Hard","Why should leaders be accountable?",
   ["They are responsible for decisions and use of public resources",
    "They should never explain their actions","They should avoid citizens",
    "They should hide public information"],"A",
   "Public money and authority belong to the people, so leaders must answer for them."),
 M(C,"Citizenship","Responsibilities","Easy","Which action demonstrates responsible citizenship?",
   ["Obeying lawful rules","Destroying public property",
    "Encouraging violence","Stealing public resources"],"A",
   "Responsible citizens obey the law and protect what belongs to everyone."),
 M(C,"Citizenship","Children's Rights","Easy","Which is a child's right?",
   ["Right to education","Right to steal",
    "Right to abuse others","Right to destroy property"],"A",
   "Every child has a right to education."),
 M(C,"Citizenship","Taxes","Medium","Why should citizens pay lawful taxes?",
   ["Taxes help government provide public services","Taxes prevent development",
    "Taxes destroy schools","Taxes stop health care"],"A",
   "Tax money pays for roads, schools, hospitals and security."),
 M(C,"Government","Arms of Government","Easy","Which arm of government makes laws?",
   ["Legislature","Judiciary","Executive","Police"],"A",
   "The Legislature, or Parliament, debates and passes laws."),
 M(C,"Government","Arms of Government","Easy","Which arm of government interprets laws?",
   ["Judiciary","Legislature","Executive","Local market"],"A",
   "Courts under the Judiciary interpret and apply the law."),
 M(C,"Government","Arms of Government","Easy","Which arm of government implements government policies?",
   ["Executive","Judiciary","Legislature","Court only"],"A",
   "The Executive carries out policies and runs the daily work of government."),
 M(C,"Independence","Meaning of Independence","Easy","What is independence?",
   ["Freedom of a country to govern itself","Rule by another country",
    "Loss of sovereignty","Absence of government"],"A",
   "An independent country makes its own laws and chooses its own leaders."),
 M(C,"Independence","Uganda's Independence","Easy","Uganda gained independence from Britain in:",
   ["1962","1950","1979","1986"],"A",
   "Uganda became independent on 9th October 1962."),
 M(C,"Independence","Uganda's Independence","Medium","Who was Uganda's first Prime Minister at independence?",
   ["Apollo Milton Obote","Idi Amin","Yoweri Museveni","Edward Mutesa II"],"A",
   "Apollo Milton Obote led the government when Uganda became independent."),
 M(C,"Independence","Importance of Independence","Medium","Why is independence important to a country?",
   ["It allows the country to govern itself","It removes all leadership",
    "It prevents development","It stops citizens from participating"],"A",
   "Independence means the people decide their own affairs."),
 M(C,"Uganda's History","Spread of Islam","Medium","Which group played a major role in spreading Islam along the East African coast?",
   ["Arab traders","Modern tourists","Railway workers","European farmers"],"A",
   "Arab traders settled along the coast and spread Islam there."),
 M(C,"Uganda's History","Traders","Easy","Why did traders visit the East African coast?",
   ["To exchange and sell goods","To stop trade",
    "To destroy markets","To prevent movement"],"A",
   "Traders came for goods such as ivory and brought items to sell in exchange."),
 M(C,"East Africa","East African Community","Easy","Which country is a member of the East African Community?",
   ["Uganda","Nigeria","Ghana","Senegal"],"A",
   "Uganda is a member state of the East African Community."),
 M(C,"East Africa","Regional Cooperation","Medium","What is one benefit of East African cooperation?",
   ["Increased regional trade and cooperation","Increased conflict",
    "Closure of all borders","Prevention of communication"],"A",
   "Working together widens markets and eases movement between member states."),
 M(C,"East Africa","Peace and Cooperation","Medium","Which activity can promote unity among East African countries?",
   ["Regional cooperation","Tribal hatred","Conflict","Discrimination"],"A",
   "Countries that cooperate build trust and shared interests."),
 M(C,"Uganda's History","Importance of History","Hard","Why should Ugandans learn about their country's history?",
   ["To understand their past and help shape the future","To forget their culture",
    "To prevent national unity","To stop development"],"A",
   "Knowing how the country came to be helps citizens make better decisions now."),
]

for _q in Q:
    _q["origin"] = ORIGIN

assert len(Q) == 100, f"expected 100 questions, got {len(Q)}"

EXTRA_FIRST = {}
EXTRA = {"P7": Q}
