#!/usr/bin/env python3
"""
p6_transport_cards.py — the owner's own 111 Q&A cards for
P.6 SST Topic 3: TRANSPORT AND COMMUNICATION IN EAST AFRICA.

Word for word, order 1-111. answer_type:
  'definition' -> cream box (black border 2.5px, rounded 16px)
  'list'       -> white pills, one per line (black border 2.5px, rounded 16px,
                  padding 12px 16px, gap 10px, font 18px bold)

Each card is (order, question, answer_type, answer_lines).
Nothing here is reworded — the text is the owner's exactly.
"""

TOPIC = "TRANSPORT AND COMMUNICATION IN EAST AFRICA"

# (order, question, type, [answer lines])
CARDS = [
    (1, "What is transport?", "definition",
     ["Transport is the movement of people and goods from one place to another."]),
    (2, "Why is transport important?", "definition",
     ["Transport helps people and goods to move from one place to another."]),
    (3, "What are the two things commonly moved by transport?", "list",
     ["People", "Goods"]),
    (4, "What are the main types of transport?", "list",
     ["Road transport", "Railway transport", "Water transport", "Air transport",
      "Pipeline transport"]),
    (5, "What is road transport?", "definition",
     ["Road transport is the movement of people and goods from one place to another using roads."]),
    (6, "What means of transport use roads?", "list",
     ["Buses", "Cars", "Lorries", "Taxis", "Motorcycles", "Bicycles"]),
    (7, "What are the advantages of road transport?", "list",
     ["Provides door-to-door services.", "Can reach many places.",
      "Is suitable for short distances.", "Can carry people and goods.",
      "Is easily available in many areas."]),
    (8, "What are the disadvantages of road transport?", "list",
     ["Can be affected by traffic jams.", "Can cause road accidents.",
      "Can be expensive for long distances.", "Can be affected by poor roads.",
      "Causes air pollution through vehicle smoke."]),
    (9, "What are some problems facing road transport in East Africa?", "list",
     ["Poor roads.", "Traffic congestion.", "Road accidents.",
      "High cost of road construction and maintenance.", "Vehicle breakdowns."]),
    (10, "What is railway transport?", "definition",
     ["Railway transport is the movement of people and goods using trains on railway lines."]),
    (11, "What are the advantages of railway transport?", "list",
     ["Carries many people.", "Carries large amounts of goods.",
      "Is suitable for long distances.", "Can reduce pressure on roads."]),
    (12, "What are the disadvantages of railway transport?", "list",
     ["Is expensive to construct.", "Cannot reach places without railway lines.",
      "May be slow compared with air transport.", "Requires regular maintenance."]),
    (13, "Name an important railway line in East Africa.", "definition",
     ["The Kenya-Uganda railway is an important railway connection between Kenya and Uganda."]),
    (14, "Why is the railway important to Uganda?", "definition",
     ["It helps to transport goods between Uganda and the Kenyan coast."]),
    (15, "What is water transport?", "definition",
     ["Water transport is the movement of people and goods by using water bodies."]),
    (16, "Where does water transport take place?", "list",
     ["Lakes", "Rivers", "Seas", "Oceans"]),
    (17, "Give examples of water transport.", "list",
     ["Boats", "Canoes", "Ferries", "Ships", "Steamers"]),
    (18, "What are the advantages of water transport?", "list",
     ["Can carry large amounts of goods.", "Is useful for long distances.",
      "Is suitable for bulky goods.", "Can be cheaper than some other forms of transport."]),
    (19, "What are the disadvantages of water transport?", "list",
     ["Is slower than air transport.", "Can be affected by storms and bad weather.",
      "Cannot be used in places without navigable water.",
      "Accidents can lead to loss of lives and property."]),
    (20, "Name some important water bodies used for transport in East Africa.", "list",
     ["Lake Victoria", "Lake Tanganyika", "Lake Albert", "Lake Kyoga",
      "Indian Ocean"]),
    (21, "What is a port?", "definition",
     ["A port is a place on the coast or a water body where ships and boats load and unload people and goods."]),
    (22, "Name an important seaport serving East Africa.", "definition",
     ["The Port of Mombasa in Kenya is an important seaport serving East African countries."]),
    (23, "Why is the Port of Mombasa important to Uganda?", "definition",
     ["It provides Uganda, a landlocked country, with an important route for importing and exporting goods through the Indian Ocean."]),
    (24, "What is air transport?", "definition",
     ["Air transport is the movement of people and goods by aircraft."]),
    (25, "What means of transport are used in air transport?", "list",
     ["Aeroplanes", "Helicopters"]),
    (26, "What are the advantages of air transport?", "list",
     ["Is the fastest means of transport.", "Is suitable for long distances.",
      "Can reach distant places quickly.", "Is useful for transporting urgent goods.",
      "Is useful for international travel."]),
    (27, "What are the disadvantages of air transport?", "list",
     ["Is expensive.", "Carries less bulky goods than ships and some trains.",
      "Can be affected by bad weather.", "Requires airports and special equipment."]),
    (28, "What is an airport?", "definition",
     ["An airport is a place where aircraft take off and land."]),
    (29, "Name an important international airport in Uganda.", "definition",
     ["Entebbe International Airport is an important international airport in Uganda."]),
    (30, "What is pipeline transport?", "definition",
     ["Pipeline transport is the movement of liquids or gases through pipes from one place to another."]),
    (31, "What can be transported through pipelines?", "list",
     ["Petroleum products", "Water", "Natural gas"]),
    (32, "What is one advantage of pipeline transport?", "definition",
     ["It can transport liquids continuously over long distances."]),
    (33, "What is one disadvantage of pipeline transport?", "definition",
     ["It is expensive to construct and maintain."]),
    (34, "What is communication?", "definition",
     ["Communication is the sending and receiving of information from one person to another."]),
    (35, "Why is communication important?", "definition",
     ["Communication helps people to share information, ideas and messages."]),
    (36, "What are the main means of communication?", "list",
     ["Telephone", "Radio", "Television", "Newspapers", "Letters", "Internet",
      "Postal services", "Face-to-face communication"]),
    (37, "What is telephone communication?", "definition",
     ["Telephone communication is the sending and receiving of information using telephones or mobile phones."]),
    (38, "What are the advantages of telephone communication?", "list",
     ["Is fast.", "Allows people to communicate over long distances.",
      "Can be used to send messages.", "Allows people to speak directly to one another."]),
    (39, "What is radio communication?", "definition",
     ["Radio communication is the sending of information through radio waves."]),
    (40, "What are the advantages of radio communication?", "list",
     ["Reaches many people.", "Provides news and information.", "Provides education.",
      "Provides entertainment.", "Can be used in many rural areas."]),
    (41, "What is television communication?", "definition",
     ["Television communication is the sharing of information through television programmes."]),
    (42, "What are the advantages of television?", "list",
     ["Provides news.", "Provides education.", "Provides entertainment.",
      "Allows people to see and hear information."]),
    (43, "What is a newspaper?", "definition",
     ["A newspaper is a printed publication containing news and other information."]),
    (44, "What information can people get from newspapers?", "list",
     ["News", "Sports", "Business information", "Government information",
      "Advertisements"]),
    (45, "What is the Internet?", "definition",
     ["The Internet is a worldwide system that allows people to share and access information using connected computers and other devices."]),
    (46, "What are some uses of the Internet?", "list",
     ["Communication", "Education", "Business", "Research", "Entertainment",
      "Sharing information"]),
    (47, "What are traditional means of communication?", "definition",
     ["Traditional means of communication are ways of passing information that were commonly used before modern communication methods became common."]),
    (48, "Give examples of traditional means of communication.", "list",
     ["Drums", "Horns", "Messengers", "Smoke signals", "Whistling", "Storytelling"]),
    (49, "How were drums used for communication?", "definition",
     ["Drums were used to send messages to people over distances, especially in communities where people understood the different drum sounds."]),
    (50, "How were messengers used for communication?", "definition",
     ["Messengers carried information from one person or place to another."]),
    (51, "What is modern communication?", "definition",
     ["Modern communication is the use of modern methods and technology to send and receive information."]),
    (52, "Give examples of modern means of communication.", "list",
     ["Mobile phones", "Radio", "Television", "Internet", "Email", "Social media"]),
    (53, "What are the advantages of modern communication?", "list",
     ["Is fast.", "Allows information to reach many people.",
      "Makes communication over long distances easier.",
      "Helps people to share information quickly.", "Supports business and education."]),
    (54, "Why are transport and communication important?", "definition",
     ["Transport and communication are important because they help people, goods and information to move from one place to another."]),
    (55, "How does transport promote trade?", "definition",
     ["Transport helps traders to move goods from places where they are produced to places where they are needed."]),
    (56, "How does communication promote trade?", "definition",
     ["Communication helps traders to obtain information about goods, prices, customers and markets."]),
    (57, "How do transport and communication promote development?", "definition",
     ["They help people to move, trade, share information and carry out different economic activities."]),
    (58, "How does transport help farmers?", "definition",
     ["Transport helps farmers to take farm products to markets and bring farm inputs to their farms."]),
    (59, "How does communication help farmers?", "definition",
     ["Communication helps farmers to receive information about weather, markets, prices and farming methods."]),
    (60, "How does transport promote tourism?", "definition",
     ["Transport enables tourists to travel to tourist attractions."]),
    (61, "How does communication promote tourism?", "definition",
     ["Communication allows tourists to obtain information about tourist attractions, accommodation and travel services."]),
    (62, "What are some problems affecting transport in East Africa?", "list",
     ["Poor roads.", "Traffic congestion.", "Road accidents.", "High transport costs.",
      "Poor railway networks.", "Bad weather.", "Lack of enough transport facilities."]),
    (63, "What are some problems affecting communication?", "list",
     ["Poor network coverage.", "High cost of communication.",
      "Lack of electricity in some areas.", "Lack of communication equipment.",
      "Poor Internet services in some areas."]),
    (64, "How does poor transport affect development?", "definition",
     ["Poor transport makes it difficult and expensive to move people and goods."]),
    (65, "How does poor communication affect development?", "definition",
     ["Poor communication makes it difficult for people to share information quickly."]),
    (66, "How can transport be improved in East Africa?", "list",
     ["Constructing and maintaining good roads.", "Improving railway networks.",
      "Improving water transport.", "Improving airports.", "Improving road safety."]),
    (67, "How can communication be improved?", "list",
     ["Expanding telephone networks.", "Improving Internet services.",
      "Increasing access to electricity.", "Building more communication facilities.",
      "Making communication services more affordable."]),
    (68, "What places should a P.6 learner be able to locate when studying transport in East Africa?", "definition",
     ["A learner should be able to locate important roads, railway lines, ports, airports, lakes and other transport routes studied in the syllabus."]),
    (69, "Name an important seaport in East Africa.", "definition",
     ["The Port of Mombasa."]),
    (70, "Which ocean is important for sea transport in East Africa?", "definition",
     ["The Indian Ocean."]),
    (71, "Name important lakes used for water transport in East Africa.", "list",
     ["Lake Victoria", "Lake Tanganyika", "Lake Albert", "Lake Kyoga"]),
    (72, "Name an important international airport in Uganda.", "definition",
     ["Entebbe International Airport."]),
    (73, "Which important railway connects Uganda with the Kenyan coast?", "definition",
     ["The Kenya-Uganda railway."]),
    (74, "What is transport? (Key definition)", "definition",
     ["Transport is the movement of people and goods from one place to another."]),
    (75, "What is communication? (Key definition)", "definition",
     ["Communication is the sending and receiving of information from one person to another."]),
    (76, "What is road transport? (Key definition)", "definition",
     ["Road transport is the movement of people and goods using roads."]),
    (77, "What is railway transport? (Key definition)", "definition",
     ["Railway transport is the movement of people and goods using trains on railway lines."]),
    (78, "What is water transport? (Key definition)", "definition",
     ["Water transport is the movement of people and goods by using water bodies."]),
    (79, "What is air transport? (Key definition)", "definition",
     ["Air transport is the movement of people and goods by aircraft."]),
    (80, "What is pipeline transport? (Key definition)", "definition",
     ["Pipeline transport is the movement of liquids or gases through pipes from one place to another."]),
    (81, "What is a port? (Key definition)", "definition",
     ["A port is a place where ships and boats load and unload people and goods."]),
    (82, "What is an airport? (Key definition)", "definition",
     ["An airport is a place where aircraft take off and land."]),
    (83, "What are the main types of transport?", "definition",
     ["Road, railway, water, air and pipeline transport."]),
    (84, "What are the main means of communication?", "definition",
     ["Telephone, radio, television, newspapers, letters, postal services and the Internet."]),
    (85, "Which is the fastest means of transport?", "definition",
     ["Air transport."]),
    (86, "Which means of transport can carry large and bulky goods?", "definition",
     ["Railway and water transport can carry large and bulky goods."]),
    (87, "Why is the Port of Mombasa important to Uganda?", "definition",
     ["It provides an important route for Uganda's imports and exports through the Indian Ocean."]),
    (88, "Why are transport and communication important? (Important facts)", "definition",
     ["They help people, goods and information to move from one place to another and promote trade and development."]),
    (89, "Define transport. (Exam)", "definition",
     ["Transport is the movement of people and goods from one place to another."]),
    (90, "Define communication. (Exam)", "definition",
     ["Communication is the sending and receiving of information from one person to another."]),
    (91, "Mention five types of transport.", "list",
     ["Road transport", "Railway transport", "Water transport", "Air transport",
      "Pipeline transport"]),
    (92, "Give four advantages of road transport.", "list",
     ["It provides door-to-door services.", "It can reach many places.",
      "It is suitable for short distances.", "It carries people and goods."]),
    (93, "Give three disadvantages of road transport.", "list",
     ["It can cause traffic jams.", "It can cause road accidents.",
      "It can be affected by poor roads."]),
    (94, "Give four advantages of water transport.", "list",
     ["It can carry large amounts of goods.", "It is suitable for bulky goods.",
      "It is useful for long distances.",
      "It can be cheaper than some other forms of transport."]),
    (95, "Mention four means of communication.", "list",
     ["Telephone", "Radio", "Television", "Internet"]),
    (96, "Give four advantages of modern communication.", "list",
     ["It is fast.", "It allows information to reach many people.",
      "It makes long-distance communication easier.",
      "It helps people to share information quickly."]),
    (97, "Mention four problems affecting transport in East Africa.", "list",
     ["Poor roads.", "Traffic congestion.", "Road accidents.", "High transport costs."]),
    (98, "Mention three problems affecting communication.", "list",
     ["Poor network coverage.", "High cost of communication.",
      "Lack of electricity in some areas."]),
    (99, "Name four traditional means of communication.", "list",
     ["Drums", "Horns", "Messengers", "Smoke signals"]),
    (100, "Mention four ways transport and communication promote development.", "list",
     ["They promote trade.", "They help farmers take products to markets.",
      "They promote tourism.", "They help people share information."]),
    (101, "What is transport? (Quick Revision)", "definition",
     ["The movement of people and goods from one place to another."]),
    (102, "What is communication? (Quick Revision)", "definition",
     ["The sending and receiving of information from one person to another."]),
    (103, "Name the five main types of transport.", "definition",
     ["Road, railway, water, air and pipeline transport."]),
    (104, "Which is the fastest means of transport? (Quick)", "definition",
     ["Air transport."]),
    (105, "Name four traditional means of communication. (Quick)", "definition",
     ["Drums, horns, messengers and smoke signals."]),
    (106, "Name four modern means of communication.", "definition",
     ["Mobile phones, radio, television and the Internet."]),
    (107, "Name an important seaport in East Africa. (Quick)", "definition",
     ["The Port of Mombasa."]),
    (108, "Name an important international airport in Uganda. (Quick)", "definition",
     ["Entebbe International Airport."]),
    (109, "Name one important railway connection involving Uganda.", "definition",
     ["The Kenya-Uganda railway."]),
    (110, "Which ocean is important for sea transport in East Africa?", "definition",
     ["The Indian Ocean."]),
    (111, "Why are transport and communication important? (Quick)", "definition",
     ["They help people, goods and information to move from one place to another and promote trade and development."]),
]

assert len(CARDS) == 111, f"expected 111 cards, got {len(CARDS)}"
assert [c[0] for c in CARDS] == list(range(1, 112)), "order_index must run 1-111"

# ---- section map: (section title, [card orders]) — owner's order 1-111 ----
SECTIONS = [
    ("1. What is transport?",                                  [1, 2, 3, 4]),
    ("2. What is road transport?",                             [5, 6, 7, 8, 9]),
    ("3. What is railway transport?",                          [10, 11, 12, 13, 14]),
    ("4. What is water transport?",                            [15, 16, 17, 18, 19, 20]),
    ("5. What is a port?",                                     [21, 22, 23]),
    ("6. What is air transport?",                              [24, 25, 26, 27, 28, 29]),
    ("7. What is pipeline transport?",                         [30, 31, 32, 33]),
    ("8. What is communication?",                              [34, 35, 36]),
    ("9. What is telephone communication?",                    [37, 38]),
    ("10. What is radio communication?",                       [39, 40]),
    ("11. What is television communication?",                  [41, 42]),
    ("12. What is a newspaper?",                               [43, 44]),
    ("13. What is the Internet?",                              [45, 46]),
    ("14. What are traditional means of communication?",       [47, 48, 49, 50]),
    ("15. What is modern communication?",                      [51, 52, 53]),
    ("16. Why are transport and communication important?",     [54, 55, 56, 57, 58, 59, 60, 61]),
    ("17. What problems affect transport and communication?",  [62, 63, 64, 65]),
    ("18. How can transport and communication be improved?",   [66, 67]),
    ("19. MAP WORK",                                           [68, 69, 70, 71, 72, 73]),
    ("KEY DEFINITIONS",                                        list(range(74, 83))),
    ("IMPORTANT FACTS TO REMEMBER",                            [83, 84, 85, 86, 87, 88]),
    ("EXAMINATION POINTS AND REVISION QUESTIONS",              list(range(89, 101))),
    ("ANSWERS TO REVISION QUESTIONS — P.6 QUICK REVISION",     list(range(101, 112))),
]

# ------------------------------------------------------------------ --
# Practice-MCQ material for the four summary sections. The learner-facing
# cards above are pinned exactly; the notes pages for these four sections
# additionally carry the classic summary structure (definition table +
# bold-led fact bullets) so the app's practice-question builders can make
# "What is meant by X?" and cloze questions from the same content.
# Every word below is taken from the owner's own 111 cards — nothing invented.

# KEY DEFINITIONS table: term | meaning (cards 74-82, minus the question tag)
DEFINITION_TABLE = [
    ("Transport", "The movement of people and goods from one place to another."),
    ("Communication", "The sending and receiving of information from one person to another."),
    ("Road transport", "The movement of people and goods from one place to another using roads."),
    ("Railway transport", "The movement of people and goods using trains on railway lines."),
    ("Water transport", "The movement of people and goods by using water bodies."),
    ("Air transport", "The movement of people and goods by aircraft."),
    ("Pipeline transport", "The movement of liquids or gases through pipes from one place to another."),
    ("Port", "A place where ships and boats load and unload people and goods."),
    ("Airport", "A place where aircraft take off and land."),
]

# IMPORTANT FACTS TO REMEMBER — bold-led bullets (cards 83-88)
FACTS = [
    "The main types of transport are **road, railway, water, air and pipeline transport**.",
    "The main means of communication are **telephone, radio, television, newspapers, letters, postal services and the Internet**.",
    "The fastest means of transport is **air transport**.",
    "**Railway and water transport** can carry large and bulky goods.",
    "The Port of Mombasa provides an important route for **Uganda's imports and exports** through the Indian Ocean.",
    "Transport and communication help people, goods and information to move from one place to another and **promote trade and development**.",
]

# EXAMINATION POINTS — bold-led bullets (cards 89-100)
EXAM_POINTS = [
    "**Transport is the movement of people and goods from one place to another.**",
    "**Communication is the sending and receiving of information from one person to another.**",
    "Five types of transport are **road, railway, water, air and pipeline transport**.",
    "Four advantages of road transport: **it provides door-to-door services; it can reach many places; it is suitable for short distances; it carries people and goods**.",
    "Three disadvantages of road transport: **it can cause traffic jams; it can cause road accidents; it can be affected by poor roads**.",
    "Four advantages of water transport: **it can carry large amounts of goods; it is suitable for bulky goods; it is useful for long distances; it can be cheaper than some other forms of transport**.",
    "Four means of communication are **telephone, radio, television and the Internet**.",
    "Four advantages of modern communication: **it is fast; it allows information to reach many people; it makes long-distance communication easier; it helps people to share information quickly**.",
    "Four problems affecting transport in East Africa: **poor roads; traffic congestion; road accidents; high transport costs**.",
    "Three problems affecting communication: **poor network coverage; high cost of communication; lack of electricity in some areas**.",
    "Four traditional means of communication are **drums, horns, messengers and smoke signals**.",
    "Four ways transport and communication promote development: **they promote trade; they help farmers take products to markets; they promote tourism; they help people share information**.",
]

# every card must appear exactly once
_all = [o for _, orders in SECTIONS for o in orders]
assert sorted(_all) == list(range(1, 112)), f"section map must cover 1-111 exactly once, got {len(_all)} cards"


def card_by_order(n):
    return CARDS[n - 1]


if __name__ == "__main__":
    print(f"{len(CARDS)} cards, {len(SECTIONS)} sections")
    ndef = sum(1 for c in CARDS if c[2] == "definition")
    nlist = sum(1 for c in CARDS if c[2] == "list")
    print(f"definitions: {ndef}, lists: {nlist}")
