#!/usr/bin/env python3
"""
batch1_p7sci.py — owner-supplied P.7 Science practice questions 001-100.

ORIGIN NOTE
    Original revision questions. NOT UNEB past-paper questions.

FACT CHECK
    All 100 scientific claims were verified independently before storage.
    No factual errors were found; no answer was changed.

REPEAT
    Q004 "Which organ is responsible for pumping blood?" asks the same thing as
    Q001 "Which organ pumps blood around the human body?", with the same answer.
    Both are kept here, but the builder serves only the first and reports it.
"""

ORIGIN = "Original practice question (not a UNEB past paper)"


def OS(topic, sub, diff, q, opts, correct, expl):
    assert len(opts) == 4 and correct in "ABCD", q
    return {"id": None, "class": "P7", "subject": "Science",
            "topic": topic, "subtopic": sub, "difficulty": diff,
            "questionType": "multiple_choice", "renderAs": "mcq",
            "question": q, "options": [f"{L}. {t}" for L, t in zip("ABCD", opts)],
            "correctAnswer": correct, "answers": None, "pairs": None,
            "explanation": expl, "origin": ORIGIN}


Q = [
 # ── TOPIC 1: HUMAN BODY (001-020) ────────────────────────────────────────
 OS("Human Body","Circulatory System","Easy","Which organ pumps blood around the human body?",
    ["Lungs","Heart","Kidney","Stomach"],"B","The heart is a muscular pump that pushes blood around the body."),
 OS("Human Body","Respiratory System","Easy","Which organ is mainly responsible for breathing?",
    ["Heart","Liver","Lungs","Kidney"],"C","The lungs take in oxygen and release carbon dioxide."),
 OS("Human Body","Skeletal System","Easy","Which part of the body protects the brain?",
    ["Rib cage","Skull","Backbone","Pelvis"],"B","The skull is a hard bony case that surrounds and protects the brain."),
 OS("Human Body","Circulatory System","Easy","Which organ is responsible for pumping blood?",
    ["Heart","Lung","Stomach","Brain"],"A","The heart pumps blood to all parts of the body."),
 OS("Human Body","Digestive System","Easy","Which part of the digestive system receives food first?",
    ["Stomach","Mouth","Small intestine","Large intestine"],"B","Food enters the body through the mouth, where chewing begins."),
 OS("Human Body","Teeth","Easy","What is the main function of the teeth?",
    ["Breathing","Pumping blood","Chewing food","Producing urine"],"C","Teeth break food into smaller pieces so it can be swallowed and digested."),
 OS("Human Body","Teeth","Medium","Which type of teeth are mainly used for cutting food?",
    ["Canines","Incisors","Molars","Premolars"],"B","Incisors are the flat front teeth used for biting and cutting."),
 OS("Human Body","Teeth","Medium","Which teeth are mainly used for tearing food?",
    ["Incisors","Canines","Molars","Premolars"],"B","Canines are pointed teeth used for tearing food."),
 OS("Human Body","Digestive System","Medium","Which organ helps to digest food in the stomach?",
    ["Digestive juices","Bones","Lungs","Skin"],"A","Digestive juices in the stomach break food down chemically."),
 OS("Human Body","Digestive System","Medium","Where does most absorption of digested food take place?",
    ["Mouth","Stomach","Small intestine","Large intestine"],"C","The small intestine has a large inner surface where digested food passes into the blood."),
 OS("Human Body","Excretory System","Easy","Which organ removes some waste products from the blood and produces urine?",
    ["Kidney","Heart","Lung","Brain"],"A","The kidneys filter the blood and form urine."),
 OS("Human Body","Nervous System","Medium","Which system controls and coordinates activities of the body?",
    ["Digestive system","Nervous system","Reproductive system","Skeletal system"],"B",
    "The nervous system sends messages that control and coordinate the body."),
 OS("Human Body","Nervous System","Easy","Which part of the nervous system controls most body activities?",
    ["Brain","Stomach","Liver","Kidney"],"A","The brain is the control centre of the nervous system."),
 OS("Human Body","Sense Organs","Easy","Which sense organ is used for seeing?",
    ["Ear","Nose","Eye","Skin"],"C","The eye detects light and lets us see."),
 OS("Human Body","Sense Organs","Easy","Which sense organ detects sound?",
    ["Eye","Ear","Nose","Tongue"],"B","The ear picks up sound waves and lets us hear."),
 OS("Human Body","Sense Organs","Easy","Which sense organ detects smells?",
    ["Nose","Eye","Ear","Skin"],"A","The nose detects smells in the air."),
 OS("Human Body","Sense Organs","Easy","Which organ helps us taste food?",
    ["Nose","Tongue","Ear","Eye"],"B","Taste buds on the tongue detect flavours."),
 OS("Human Body","Sense Organs","Easy","Which organ detects touch?",
    ["Skin","Heart","Liver","Lung"],"A","The skin contains nerve endings that sense touch, heat and pain."),
 OS("Human Body","Skeletal System","Medium","What is the main function of the skeleton?",
    ["To digest food","To support and protect the body","To pump blood","To produce saliva"],"B",
    "The skeleton gives the body shape, supports it and protects soft organs."),
 OS("Human Body","Skeletal System","Medium","Which part joins one bone to another bone?",
    ["Muscle","Joint","Skin","Nerve"],"B","A joint is the place where two bones meet."),

 # ── TOPIC 2: REPRODUCTION AND GROWTH (021-035) ───────────────────────────
 OS("Reproduction","Meaning of Reproduction","Easy","What is reproduction?",
    ["Movement from one place to another","Production of new organisms",
     "Removal of waste","Digestion of food"],"B","Reproduction is how living things produce new individuals of their kind."),
 OS("Reproduction","Male Reproductive System","Easy","Which organ produces sperm in males?",
    ["Ovary","Testis","Uterus","Kidney"],"B","The testes produce sperm cells."),
 OS("Reproduction","Female Reproductive System","Easy","Which organ produces ova in females?",
    ["Testis","Ovary","Penis","Kidney"],"B","The ovaries produce ova, or egg cells."),
 OS("Reproduction","Pregnancy","Easy","Where does the baby develop before birth?",
    ["Stomach","Uterus","Kidney","Small intestine"],"B","The baby grows in the uterus, also called the womb."),
 OS("Reproduction","Fertilisation","Medium","What is fertilisation?",
    ["The development of a baby after birth","Fusion of male and female sex cells",
     "Growth of bones","Production of urine"],"B","Fertilisation happens when a sperm joins with an ovum."),
 OS("Reproduction","Sex Cells","Easy","Which is the male sex cell?",
    ["Ovum","Sperm","Zygote","Embryo"],"B","The sperm is the male sex cell."),
 OS("Reproduction","Sex Cells","Easy","Which is the female sex cell?",
    ["Sperm","Ovum","Embryo","Foetus"],"B","The ovum, or egg, is the female sex cell."),
 OS("Growth and Development","Puberty","Medium","What is puberty?",
    ["A period when a child stops growing","A period of physical and sexual development",
     "A period of sleeping","A period of illness"],"B",
    "Puberty is the stage when the body changes from a child's into an adult's."),
 OS("Growth and Development","Puberty","Medium","Which change commonly occurs in boys during puberty?",
    ["Development of a deeper voice","Loss of all teeth","Becoming shorter","Stopping body growth"],"A",
    "The voice box grows during puberty, so a boy's voice becomes deeper."),
 OS("Growth and Development","Puberty","Medium","Which change commonly occurs in girls during puberty?",
    ["Menstruation begins","The heart stops growing","All teeth fall out","Breathing stops"],"A",
    "Menstruation starting is one of the main changes of puberty in girls."),
 OS("Growth and Development","Menstruation","Medium","What is menstruation?",
    ["Release of an egg from the ovary","Monthly shedding of the uterine lining",
     "Production of sperm","Digestion of food"],"B",
    "If no fertilisation happens, the lining of the uterus is shed each month."),
 OS("Reproduction","Pregnancy","Easy","What is the period from fertilisation until birth called?",
    ["Pregnancy","Digestion","Respiration","Excretion"],"A","Pregnancy is the time a baby develops inside the uterus."),
 OS("Growth and Development","Nutrition and Growth","Easy","Which substance is important for the growth of strong bones?",
    ["Calcium","Salt only","Sugar","Alcohol"],"A","Calcium builds strong bones and teeth."),
 OS("Growth and Development","Personal Hygiene","Easy","Which practice helps adolescents maintain good personal hygiene?",
    ["Avoiding bathing","Washing the body regularly","Sharing dirty clothes","Avoiding clean water"],"B",
    "Regular washing removes sweat and germs and prevents body odour."),
 OS("Growth and Development","Nutrition and Growth","Medium","Why should adolescents eat a balanced diet?",
    ["To support healthy growth and development","To stop growing",
     "To avoid drinking water","To prevent all movement"],"A",
    "The body grows fast during adolescence and needs all the nutrient groups."),

 # ── TOPIC 3: FOOD AND NUTRITION (036-055) ────────────────────────────────
 OS("Food and Nutrition","Nutrients","Easy","Which nutrient mainly provides energy to the body?",
    ["Carbohydrates","Vitamins","Minerals","Water"],"A","Carbohydrates such as cassava and posho are the body's main energy foods."),
 OS("Food and Nutrition","Nutrients","Easy","Which nutrient is mainly needed for growth and repair of body tissues?",
    ["Protein","Water","Fibre","Vitamins"],"A","Proteins build new tissue and repair damaged tissue."),
 OS("Food and Nutrition","Nutrients","Medium","Which nutrient provides a concentrated source of energy?",
    ["Fat","Water","Mineral salts","Fibre"],"A","Fats and oils give more energy per gram than any other nutrient."),
 OS("Food and Nutrition","Vitamins","Medium","Which vitamin helps maintain good eyesight?",
    ["Vitamin A","Vitamin C","Vitamin D","Vitamin K"],"A","Vitamin A, found in foods such as carrots, helps healthy eyesight."),
 OS("Food and Nutrition","Vitamins","Medium","Which vitamin helps the body absorb calcium and supports healthy bones?",
    ["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],"D","Vitamin D helps the body take in calcium for strong bones."),
 OS("Food and Nutrition","Minerals","Medium","Which mineral is important for making haemoglobin?",
    ["Iron","Calcium","Iodine","Sodium"],"A","Iron is needed to make haemoglobin, which carries oxygen in the blood."),
 OS("Food and Nutrition","Deficiency Diseases","Medium","Lack of iron in the diet may cause:",
    ["Anaemia","Malaria","Broken bones","Tooth decay only"],"A",
    "Without enough iron the blood cannot carry oxygen well, causing anaemia."),
 OS("Food and Nutrition","Food Sources","Easy","Which food is a good source of protein?",
    ["Beans","Sugar","Salt","Cooking oil"],"A","Beans, groundnuts, fish, meat and eggs are protein foods."),
 OS("Food and Nutrition","Food Sources","Easy","Which food is rich in carbohydrates?",
    ["Cassava","Fish","Eggs","Meat"],"A","Cassava, posho, rice and potatoes are energy-giving carbohydrate foods."),
 OS("Food and Nutrition","Food Sources","Easy","Which food is a good source of vitamins?",
    ["Fruits","Salt","Cooking oil","Sugar"],"A","Fruits and vegetables are rich in vitamins."),
 OS("Food and Nutrition","Balanced Diet","Medium","What is a balanced diet?",
    ["A diet containing only carbohydrates","A diet containing nutrients in appropriate amounts",
     "A diet containing only fruits","A diet containing only meat"],"B",
    "A balanced diet has all the nutrient groups in the right amounts."),
 OS("Food and Nutrition","Water","Easy","Why is water important to the body?",
    ["It helps regulate body processes","It replaces bones","It produces teeth","It stops digestion"],"A",
    "Water carries nutrients, removes waste and helps control body temperature."),
 OS("Food and Nutrition","Food Sources","Easy","Which food is most likely to contain a large amount of fat?",
    ["Cooking oil","Orange","Cassava","Watermelon"],"A","Cooking oil is almost entirely fat."),
 OS("Food and Nutrition","Fibre","Medium","What is dietary fibre important for?",
    ["Healthy digestion","Producing bones","Pumping blood","Hearing"],"A",
    "Fibre helps food move through the gut and prevents constipation."),
 OS("Food and Nutrition","Deficiency Diseases","Hard","Which condition can result from severe lack of protein and energy in young children?",
    ["Malnutrition","Broken arm","Common cold","Tooth brushing"],"A",
    "Long-term shortage of protein and energy leads to malnutrition."),
 OS("Food and Nutrition","Food Hygiene","Easy","Why should fruits and vegetables be washed before eating?",
    ["To remove dirt and some harmful microorganisms","To increase their size",
     "To remove all nutrients","To make them poisonous"],"A",
    "Washing removes soil, chemicals and germs that could cause illness."),
 OS("Food and Nutrition","Food Preservation","Easy","Which method helps preserve food?",
    ["Drying","Leaving food uncovered","Adding dirt","Keeping food in sunlight indefinitely"],"A",
    "Drying, smoking, salting and refrigeration all preserve food."),
 OS("Food and Nutrition","Food Preservation","Medium","Which food preservation method involves removing water from food?",
    ["Drying","Boiling","Washing","Cutting"],"A",
    "Drying removes the moisture that germs need in order to grow."),
 OS("Food and Nutrition","Food Hygiene","Easy","Why should cooked food be covered?",
    ["To protect it from contamination","To make it dirty","To increase insects","To reduce its nutrients"],"A",
    "Covering food keeps out flies, dust and germs."),
 OS("Food and Nutrition","Healthy Eating","Easy","Which habit promotes good nutrition?",
    ["Eating a variety of foods","Eating only sweets","Skipping all meals","Drinking dirty water"],"A",
    "Eating different foods supplies all the nutrients the body needs."),

 # ── TOPIC 4: DISEASES AND HEALTH (056-075) ───────────────────────────────
 OS("Diseases","Malaria","Medium","Which organism causes malaria?",
    ["Bacterium","Plasmodium","Virus","Worm"],"B","Malaria is caused by a tiny parasite called Plasmodium."),
 OS("Diseases","Malaria","Medium","Malaria is commonly transmitted by:",
    ["Female Anopheles mosquito","Housefly","Cockroach","Tsetse fly"],"A",
    "The female Anopheles mosquito carries the malaria parasite from person to person."),
 OS("Diseases","Disease Prevention","Easy","Which method helps prevent malaria?",
    ["Sleeping under an insecticide-treated mosquito net","Drinking dirty water",
     "Leaving stagnant water everywhere","Avoiding bathing"],"A",
    "A treated net stops mosquito bites while you sleep."),
 OS("Diseases","HIV and AIDS","Medium","Which disease is caused by HIV?",
    ["HIV infection/AIDS","Malaria","Ringworm","Cholera"],"A",
    "HIV weakens the body's defence system and can lead to AIDS."),
 OS("Diseases","HIV and AIDS","Medium","HIV can be transmitted through:",
    ["Sharing food","Unprotected sexual contact","Shaking hands","Sitting near an infected person"],"B",
    "HIV spreads through certain body fluids, not through ordinary daily contact."),
 OS("Diseases","Waterborne Diseases","Medium","Which disease is commonly spread through contaminated food and water?",
    ["Cholera","Malaria","HIV","Ringworm"],"A","Cholera spreads through water or food contaminated with the germ."),
 OS("Diseases","Disease Prevention","Easy","Which practice helps prevent cholera?",
    ["Drinking treated or safe water","Eating uncovered food",
     "Defecating near water sources","Leaving rubbish everywhere"],"A",
    "Boiling or treating water kills the germs that cause cholera."),
 OS("Diseases","Tuberculosis","Medium","Which organism commonly causes tuberculosis?",
    ["Bacterium","Mosquito","Protozoan only","Worm"],"A","Tuberculosis is caused by a bacterium."),
 OS("Diseases","Tuberculosis","Medium","Tuberculosis mainly affects which organ?",
    ["Lungs","Bones only","Teeth","Skin only"],"A","TB most commonly attacks the lungs, causing a long cough."),
 OS("Diseases","Types of Disease","Medium","Which disease is caused by a virus?",
    ["Measles","Malaria","Ringworm","Hookworm"],"A","Measles is a viral disease that spreads easily from person to person."),
 OS("Diseases","Disease Prevention","Easy","Which practice reduces the spread of infectious diseases?",
    ["Washing hands with soap and clean water","Sharing used needles",
     "Drinking unsafe water","Leaving wounds uncovered"],"A",
    "Handwashing removes germs before they reach the mouth or a wound."),
 OS("Health","First Aid","Easy","Why should wounds be cleaned?",
    ["To reduce the risk of infection","To increase germs",
     "To make the wound larger","To stop blood circulation"],"A",
    "Cleaning removes dirt and germs that could infect the wound."),
 OS("Health","Immunisation","Medium","What is vaccination?",
    ["Giving a substance that helps the body develop protection against a disease",
     "Giving contaminated food","Removing all blood","Giving only painkillers"],"A",
    "A vaccine trains the body's defences to fight a disease before it strikes."),
 OS("Health","Immunisation","Medium","Which disease can be prevented by vaccination?",
    ["Measles","Malaria in all cases","Broken bones","Tooth decay"],"A",
    "Measles is prevented by immunisation given in childhood."),
 OS("Diseases","Vectors","Medium","Which insect can transmit sleeping sickness?",
    ["Tsetse fly","Housefly","Butterfly","Bee"],"A","The tsetse fly carries the parasite that causes sleeping sickness."),
 OS("Diseases","Deficiency Diseases","Hard","Which disease is associated with lack of vitamin C?",
    ["Scurvy","Rickets","Anaemia","Malaria"],"A","Too little vitamin C causes scurvy, with bleeding gums and weakness."),
 OS("Diseases","Deficiency Diseases","Hard","Which disease is associated with lack of vitamin D?",
    ["Rickets","Cholera","Malaria","Dysentery"],"A","Without vitamin D bones grow weak and bend, a condition called rickets."),
 OS("Diseases","Deficiency Diseases","Hard","Which condition may result from lack of iodine?",
    ["Goitre","Malaria","Cholera","Ringworm"],"A","Lack of iodine makes the thyroid gland swell, which is called goitre."),
 OS("Diseases","Disease Prevention","Easy","Which practice helps prevent intestinal worms?",
    ["Washing hands before eating","Eating soil","Drinking untreated water","Walking barefoot everywhere"],"A",
    "Clean hands stop worm eggs from being swallowed with food."),
 OS("Health","Sanitation","Easy","Why should toilets and latrines be kept clean?",
    ["To reduce the spread of disease","To attract flies",
     "To contaminate water","To increase bad smells"],"A",
    "Clean latrines keep flies away and stop germs reaching food and water."),

 # ── TOPIC 5: PLANTS (076-090) ────────────────────────────────────────────
 OS("Plants","Plant Parts","Easy","Which part of a plant absorbs water and mineral salts from the soil?",
    ["Root","Leaf","Flower","Fruit"],"A","Roots take in water and dissolved minerals from the soil."),
 OS("Plants","Plant Parts","Easy","Which part of a plant mainly makes food?",
    ["Root","Leaf","Flower","Seed"],"B","Leaves make food because they contain chlorophyll and catch sunlight."),
 OS("Plants","Photosynthesis","Easy","What process do green plants use to make food?",
    ["Photosynthesis","Digestion","Respiration only","Excretion"],"A",
    "Photosynthesis is how green plants use sunlight to make their own food."),
 OS("Plants","Photosynthesis","Medium","Which gas is needed by green plants for photosynthesis?",
    ["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"],"C","Plants take in carbon dioxide from the air to make food."),
 OS("Plants","Photosynthesis","Medium","Which gas is released during photosynthesis?",
    ["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"],"B","Oxygen is given off as a by-product of photosynthesis."),
 OS("Plants","Photosynthesis","Medium","What is the green pigment in leaves called?",
    ["Chlorophyll","Haemoglobin","Melanin","Keratin"],"A","Chlorophyll gives leaves their green colour and traps sunlight."),
 OS("Plants","Photosynthesis","Medium","Which condition is necessary for photosynthesis?",
    ["Light","Darkness only","Lack of water","Lack of carbon dioxide"],"A",
    "Plants need light energy to make food; the process stops in the dark."),
 OS("Plants","Plant Parts","Medium","What is the main function of the stem?",
    ["Support the plant and transport substances","Digest food","Produce urine","Hear sounds"],"A",
    "The stem holds the plant up and carries water and food between roots and leaves."),
 OS("Plants","Flowers","Medium","Which part of a flower produces pollen?",
    ["Anther","Ovary","Stigma","Sepal"],"A","The anther is the part of the stamen that makes pollen."),
 OS("Plants","Flowers","Medium","Which part of a flower receives pollen?",
    ["Stigma","Anther","Root","Leaf"],"A","The stigma is the sticky top of the pistil where pollen lands."),
 OS("Plants","Pollination","Medium","What is pollination?",
    ["Transfer of pollen from anther to stigma","Formation of roots",
     "Absorption of water","Production of leaves"],"A",
    "Pollination is the movement of pollen from the anther to the stigma."),
 OS("Plants","Pollination","Easy","Which agent can help transfer pollen between flowers?",
    ["Insects","Stones","Soil only","Roots"],"A","Insects such as bees carry pollen as they move between flowers."),
 OS("Plants","Germination","Medium","What is germination?",
    ["Development of a seed into a young plant","Production of pollen",
     "Formation of fruit only","Absorption of sunlight"],"A",
    "Germination is when a seed begins to grow into a seedling."),
 OS("Plants","Germination","Easy","Which condition is necessary for most seeds to germinate?",
    ["Water","Cooking oil","Salt water only","Complete dryness"],"A",
    "Seeds need water, warmth and air to germinate."),
 OS("Plants","Seeds","Hard","Which part of a seed develops into the young shoot?",
    ["Plumule","Radicle","Seed coat","Cotyledon only"],"A",
    "The plumule grows upward into the shoot, while the radicle grows down into the root."),

 # ── TOPIC 6: ANIMALS (091-100) ───────────────────────────────────────────
 OS("Animals","Feeding Habits","Easy","Animals that feed mainly on plants are called:",
    ["Carnivores","Herbivores","Omnivores","Parasites"],"B","Herbivores are plant eaters, such as cows and goats."),
 OS("Animals","Feeding Habits","Easy","Animals that feed mainly on other animals are called:",
    ["Herbivores","Carnivores","Producers","Decomposers"],"B","Carnivores are flesh eaters, such as lions."),
 OS("Animals","Feeding Habits","Easy","Animals that eat both plants and animals are called:",
    ["Herbivores","Carnivores","Omnivores","Producers"],"C","Omnivores eat both plant and animal food."),
 OS("Animals","Feeding Habits","Easy","Which animal is a herbivore?",
    ["Cow","Lion","Eagle","Cat"],"A","A cow feeds on grass and other plants."),
 OS("Animals","Feeding Habits","Easy","Which animal is a carnivore?",
    ["Goat","Cow","Lion","Rabbit"],"C","A lion hunts and eats other animals."),
 OS("Animals","Feeding Habits","Medium","Which animal is an omnivore?",
    ["Cow","Human being","Goat","Sheep"],"B","Human beings eat both plants and animal products."),
 OS("Animals","Animal Groups","Easy","Which group of animals has feathers?",
    ["Mammals","Birds","Fish","Reptiles"],"B","Feathers are found only on birds."),
 OS("Animals","Animal Groups","Medium","Which group of animals has scales and usually breathes through gills?",
    ["Fish","Birds","Mammals","Insects"],"A","Fish have scales and take oxygen from water using gills."),
 OS("Animals","Animal Groups","Easy","Which group of animals feeds its young with milk?",
    ["Birds","Mammals","Fish","Reptiles"],"B","Mammals feed their young on milk produced by the mother."),
 OS("Animals","Adaptation","Medium","Which organ helps fish obtain oxygen from water?",
    ["Lungs","Gills","Skin only","Feathers"],"B","Gills take dissolved oxygen out of the water."),
]

assert len(Q) == 100, f"expected 100 questions, got {len(Q)}"
EXTRA = {"P7": Q}
