#!/usr/bin/env python3
"""
build_practice_bank.py — four SEPARATE Ugandan SST practice datasets (P4, P5, P6, P7).

Original questions written for this app. No PLE paper is copied.
Every record carries its class in both the `class` field and the ID prefix, so a
mismatch is detectable two ways.

Render types (how the app draws it) vs questionType (the pedagogical label):
  mcq   -> A/B/C/D buttons        (multiple_choice, scenario, comparison,
                                   cause_effect, application, map_skill, identification)
  tf    -> True/False buttons     (true_false)
  fill  -> typed answer           (fill_blank, short_answer)
  match -> tap-to-pair            (matching)
"""
import json, os, sys, glob, importlib.util
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qhelpers import M as _M, T as _T, F as _F, P as _P

# The base lists below were written with an explicit number argument.
# Numbers are now assigned by the builder, so swallow and ignore them.
def M(cls, n, *a, **k): k.pop("code", None); return _M(cls, *a, **k)
def T(cls, n, *a, **k): k.pop("code", None); return _T(cls, *a, **k)
def F(cls, n, *a, **k): k.pop("code", None); return _F(cls, *a, **k)
def P(cls, n, *a, **k): k.pop("code", None); return _P(cls, *a, **k)

OUT = "data/practice"


# ══════════════════════════════════════════════════════════════════════════
# P.4 — the learner's own community, school, family, district. Nothing wider.
# ══════════════════════════════════════════════════════════════════════════
P4 = [
 F("P4",1,"Our Community","What is a community","Easy",
   "A group of people who live together in the same area is called a ______.",
   ["community"],"A community is people living together in one area and sharing things like schools and markets."),
 M("P4",2,"Our Community","Community services","Easy",
   "Which one of these gives health services in a community?",
   ["Market","Health centre","Bus park","Playground"],"B",
   "A health centre is where people go when they are sick."),
 M("P4",3,"Our Community","Community workers","Easy",
   "Who keeps law and order in a community?",
   ["A teacher","A police officer","A farmer","A shopkeeper"],"B",
   "Police officers protect people and keep peace in the community."),
 P("P4",4,"Our Community","Community workers","Medium",
   "Match each worker with the place where they work.",
   [["Teacher","School"],["Doctor","Health centre"],["Police officer","Police post"],["Farmer","Garden"]],
   "Every community worker has a place where they do their work."),
 F("P4",5,"Our Family","Types of family","Easy",
   "A family with a father, a mother and their children only is called a ______ family.",
   ["nuclear"],"A nuclear family is small: parents and their own children."),
 M("P4",6,"Our Family","Types of family","Medium",
   "Which person belongs to an extended family but NOT to a nuclear family?",
   ["Father","Mother","Uncle","Daughter"],"C",
   "An extended family adds relatives like uncles, aunts and grandparents."),
 M("P4",7,"Our Family","Family needs","Easy",
   "Which one is a basic need of every family?",
   ["Television","Food","Radio","Bicycle"],"B",
   "Food, clothing and shelter are basic needs. Others are wants."),
 M("P4",8,"Our School","School leaders","Easy",
   "Who is the head of a primary school?",
   ["Class monitor","Head teacher","Head prefect","Parent"],"B",
   "The head teacher leads the school and all its teachers."),
 T("P4",9,"Our School","School rules","Easy",
   "A school timetable helps learners know what to do at each time of the day.","A",
   "A timetable organises the school day so everyone knows what comes next."),
 M("P4",10,"Our School","School rules","Medium",
   "Why does a school have rules?",
   ["To punish learners","To keep order and safety","To make school hard","To stop learning"],"B",
   "Rules keep everyone safe and help the school run well."),
 M("P4",11,"Leadership","Local leaders","Medium",
   "Who leads a village in Uganda?",
   ["The LC I chairperson","The President","The head teacher","The district chairperson"],"A",
   "The LC I chairperson is the leader closest to the people in a village."),
 M("P4",12,"Leadership","Good citizenship","Medium",
   "Amina finds a pen that belongs to her classmate. What is the right thing to do?",
   ["Keep the pen","Give it back to the owner","Sell the pen","Hide the pen"],"B",
   "Returning what is not yours shows honesty, which is good citizenship.",
   "scenario"),
 F("P4",13,"Our District","Uganda","Easy",
   "The capital city of Uganda is ______.",["kampala"],
   "Kampala is Uganda's capital city and its biggest town."),
 M("P4",14,"Our District","Regions","Medium",
   "How many main regions does Uganda have?",["Two","Three","Four","Five"],"C",
   "Uganda has four regions: Central, Eastern, Northern and Western."),
 M("P4",15,"Our District","Regions","Medium",
   "In which region of Uganda is Kampala found?",
   ["Eastern","Central","Northern","Western"],"B",
   "Kampala is in the Central region of Uganda."),
 M("P4",16,"Weather","Weather instruments","Easy",
   "Which instrument measures the amount of rainfall?",
   ["Wind vane","Rain gauge","Windsock","Ruler"],"B",
   "A rain gauge collects rain so we can measure how much fell."),
 T("P4",17,"Weather","Weather instruments","Easy",
   "A wind vane shows the direction from which the wind is blowing.","A",
   "A wind vane turns to point to where the wind comes from."),
 M("P4",18,"Weather","Weather and activities","Medium",
   "A farmer wants to dry maize. Which weather is best?",
   ["Rainy","Cloudy","Sunny","Foggy"],"C",
   "Sunshine dries crops quickly and keeps them from rotting.","scenario"),
 M("P4",19,"Direction","Cardinal points","Easy",
   "How many cardinal points are there?",["Two","Four","Six","Eight"],"B",
   "The four cardinal points are North, East, South and West."),
 F("P4",20,"Direction","Cardinal points","Easy",
   "The sun rises in the ______.",["east"],
   "The sun always rises in the east and sets in the west."),
 M("P4",21,"Direction","Using direction","Medium",
   "If you face East, which direction is behind you?",
   ["North","South","West","East"],"C",
   "West is directly opposite East, so it is behind you.","application"),
 M("P4",22,"Map Skills","Map symbols","Medium",
   "On a map, what usually shows water such as a lake?",
   ["Green colour","Blue colour","Brown colour","Yellow colour"],"B",
   "Map makers use blue for water bodies like lakes and rivers."),
 M("P4",23,"Transport","Means of transport","Easy",
   "Which means of transport moves on a road?",
   ["Aeroplane","Bus","Ship","Train"],"B",
   "Buses use roads. Trains use railways, ships use water, planes use air."),
 F("P4",24,"Communication","Sending messages","Easy",
   "A letter is sent to another town through the ______ office.",["post"],
   "The post office collects and delivers letters and parcels."),
 M("P4",25,"Communication","Modern communication","Easy",
   "Which one is a modern means of communication?",
   ["Drum","Mobile phone","Smoke signal","Horn"],"B",
   "A mobile phone is modern. Drums and smoke were used long ago."),
 F("P4",26,"Occupations","Community jobs","Easy",
   "A person who treats sick people is called a ______.",["doctor"],
   "Doctors examine and treat sick people at health centres and hospitals."),
 F("P4",27,"Markets","Buying and selling","Easy",
   "A place where people buy and sell goods is called a ______.",["market"],
   "A market brings buyers and sellers together in one place."),
 M("P4",28,"Agriculture","Farm tools","Easy",
   "Which one is a tool used by a farmer?",
   ["Hoe","Chalk","Stethoscope","Chalkboard"],"A",
   "A hoe is used for digging and weeding in the garden."),
 F("P4",29,"National Identity","National symbols","Medium",
   "The national motto of Uganda is 'For God and My ______'.",["country"],
   "Uganda's motto is 'For God and My Country'."),
 M("P4",30,"National Identity","National flag","Medium",
   "Which colour is at the top of the Uganda national flag?",
   ["Yellow","Red","Black","White"],"C",
   "The Uganda flag starts with black at the top, then yellow, then red."),
 F("P4",31,"National Identity","Coat of arms","Medium",
   "The bird found on Uganda's Coat of Arms is the crested ______.",["crane"],
   "The crested crane is Uganda's national bird."),
 M("P4",32,"Culture","Traditional practices","Medium",
   "Which one is a way of passing on culture to children?",
   ["Telling folk stories","Watching cars","Sleeping","Digging alone"],"A",
   "Elders pass on culture through stories, songs, proverbs and dances."),
 M("P4",33,"Health","Keeping clean","Easy",
   "Washing hands before eating helps to prevent ______.",
   ["Rain","Diseases","Wind","Noise"],"B",
   "Clean hands stop germs from entering the body with food."),
 M("P4",34,"Health","Sanitation","Medium",
   "Which one keeps the school compound clean?",
   ["Sweeping and collecting rubbish","Throwing papers around","Leaving food remains","Blocking drains"],"A",
   "Sweeping and collecting rubbish stops flies and diseases."),
 M("P4",35,"Safety","Road safety","Medium",
   "Before crossing a road, you should look ______.",
   ["Only to the left","Only to the right","Both sides","At the sky"],"C",
   "Look both ways so you can see vehicles coming from either direction."),
 M("P4",36,"Safety","Emergencies","Medium",
   "You see a fire starting in the kitchen at home. What should you do first?",
   ["Watch it burn","Tell an adult at once","Run and hide","Add more firewood"],"B",
   "Telling an adult immediately brings help before the fire spreads.","scenario"),
 F("P4",37,"Environment","Natural resources","Medium",
   "Water, soil, trees and air are all called ______ resources.",["natural"],
   "Natural resources are useful things we get from nature, not from factories."),
 T("P4",38,"Environment","Conservation","Medium",
   "Cutting down all the trees in an area is good for the environment.","B",
   "Cutting all trees causes soil erosion and less rain. We should plant more trees."),
 M("P4",39,"Direction","Using direction","Hard",
   "The school is to the North of the church. In which direction is the church from the school?",
   ["North","South","East","West"],"B",
   "If A is north of B, then B must be south of A. Directions work both ways.","application"),
 M("P4",40,"Markets","Trade","Hard",
   "How is a market different from a shop?",
   ["A market has many sellers in one open place, a shop usually has one seller",
    "A market sells nothing","A shop has many sellers","They are exactly the same"],"A",
   "A market brings many traders together; a shop is usually run by one trader.","comparison"),
 M("P4",41,"Our Community","Community services","Hard",
   "Why is it important for a village to have a health centre nearby?",
   ["So people travel far when sick","So sick people get treatment quickly",
    "So the village looks big","So children stay home"],"B",
   "A nearby health centre means help arrives before an illness gets worse.","cause_effect"),
 M("P4",42,"Health","Sanitation","Hard",
   "Your class wants to keep the classroom clean all week. Which plan works best?",
   ["Everybody cleans on Friday only","Make a duty rota so a group cleans each day",
    "Wait for the teacher to clean","Clean only when visitors come"],"B",
   "A duty rota shares the work fairly and keeps the room clean every day.","scenario"),
 M("P4",43,"Leadership","Local leaders","Hard",
   "Why should children know the leaders of their village?",
   ["To play with them","To know who to report a problem to",
    "To copy their clothes","To avoid school"],"B",
   "Knowing your leaders means you know where to go for help.","application"),
]


# ══════════════════════════════════════════════════════════════════════════
# P.5 — Uganda as a whole: regions, features, resources, map skills.
# ══════════════════════════════════════════════════════════════════════════
P5 = [
 M("P5",1,"Physical Features","Lakes","Easy",
   "Which is the largest lake in Uganda?",["Lake Kyoga","Lake Albert","Lake Victoria","Lake Edward"],"C",
   "Lake Victoria is the largest lake in Uganda and in Africa."),
 M("P5",2,"Physical Features","Mountains","Easy",
   "In which part of Uganda is Mount Rwenzori found?",["Eastern","Western","Northern","Central"],"B",
   "Mount Rwenzori lies in western Uganda, on the border with the D.R. Congo."),
 F("P5",3,"Physical Features","Mountains","Medium",
   "The highest peak of Mount Rwenzori is called ______ peak.",["margherita"],
   "Margherita is the highest peak of Mount Rwenzori."),
 M("P5",4,"Physical Features","Lake formation","Hard",
   "Lake Albert was formed mainly by ______.",
   ["Faulting","River deposits","Volcanic action","Wind action"],"A",
   "Lake Albert lies in the Rift Valley, which was formed by faulting."),
 M("P5",5,"Climate","Climate types","Medium",
   "Which type of climate is found around Lake Victoria?",
   ["Desert","Equatorial","Mediterranean","Temperate"],"B",
   "The Lake Victoria area has an equatorial climate: warm with rain most of the year."),
 M("P5",6,"Climate","Rainfall","Medium",
   "Which part of Uganda receives the least rainfall?",
   ["Kalangala","Karamoja","Kabale","Mukono"],"B",
   "Karamoja is semi-arid, so it gets little and unreliable rainfall."),
 M("P5",7,"Vegetation","Vegetation types","Medium",
   "Which vegetation type covers most of Karamoja?",
   ["Tropical rain forest","Savanna grassland with thorny bushes","Mangrove forest","Montane forest"],"B",
   "Dry savanna with thorny bushes suits areas with low rainfall like Karamoja."),
 M("P5",8,"Soils","Soil types","Medium",
   "Which soil type is best for growing most crops?",
   ["Sandy soil","Clay soil","Loam soil","Murram"],"C",
   "Loam soil holds water well and is rich in plant food."),
 F("P5",9,"Natural Resources","Minerals","Medium",
   "Copper used to be mined at ______ in Kasese district.",["kilembe"],
   "Kilembe mines in Kasese are known for copper."),
 M("P5",10,"Natural Resources","Minerals","Medium",
   "Limestone used for making cement is mined at ______.",
   ["Tororo","Gulu","Arua","Soroti"],"A",
   "Tororo has limestone deposits used in the cement industry."),
 F("P5",11,"Agriculture","Types of farming","Medium",
   "Growing crops mainly for selling is called ______ farming.",["commercial"],
   "Commercial farming produces for sale; subsistence farming is for the family."),
 M("P5",12,"Agriculture","Cash crops","Hard",
   "Which cash crop grows best on the slopes of Mount Elgon?",
   ["Cotton","Arabica coffee","Rice","Sisal"],"B",
   "The cool, high slopes of Mt Elgon suit Arabica coffee."),
 M("P5",13,"Fishing","Fishing grounds","Easy",
   "Which lake supplies the largest amount of fish in Uganda?",
   ["Lake Victoria","Lake Bunyonyi","Lake Wamala","Lake Nakivale"],"A",
   "Lake Victoria is Uganda's biggest source of fish."),
 M("P5",14,"Fishing","Bad fishing methods","Hard",
   "Why is fishing using poison discouraged?",
   ["It increases fish","It kills young fish and pollutes the water","It cleans the water","It helps fish breed"],"B",
   "Poison kills fish of all sizes and makes the water unsafe.","cause_effect"),
 F("P5",15,"Population","Census","Medium",
   "The official counting of all people in a country is called a population ______.",["census"],
   "A census counts people and collects information for planning."),
 M("P5",16,"Population","Population density","Medium",
   "An area with very many people living in it is said to be ______.",
   ["Sparsely populated","Densely populated","Empty","Rural"],"B",
   "Densely populated means many people live in a small area."),
 M("P5",17,"Settlement","Reasons for settlement","Medium",
   "Why do many people settle near lakes?",
   ["It is cold there","There is water, fish and fertile soil","There are no roads","The land is rocky"],"B",
   "Water, fish and fertile soils attract settlement."),
 M("P5",18,"Leadership","Local government","Medium",
   "Who is the political head of a district in Uganda?",
   ["The LC I chairperson","The LC V chairperson","The head teacher","The Resident District Commissioner"],"B",
   "The LC V chairperson is the elected political head of a district."),
 F("P5",19,"History","Independence","Easy",
   "Uganda got her independence in the year ______.",["1962"],
   "Uganda became independent on 9th October 1962."),
 M("P5",20,"Citizenship","Voting","Medium",
   "At what age can a Ugandan citizen vote in national elections?",
   ["16 years","18 years","21 years","25 years"],"B",
   "Ugandans aged 18 years and above are allowed to vote."),
 F("P5",21,"Map Skills","Map elements","Easy",
   "The part of a map that explains what the symbols mean is called the ______.",["key","legend"],
   "The key (or legend) explains the symbols used on a map."),
 M("P5",22,"Map Skills","Scale","Hard",
   "On a map with a scale of 1:50,000, one centimetre represents ______ on the ground.",
   ["500 metres","5 kilometres","50 metres","5,000 metres"],"A",
   "1 cm stands for 50,000 cm, and 50,000 cm is 500 metres.","map_skill"),
 F("P5",23,"Map Skills","Direction","Medium",
   "The direction exactly between North and East is called ______.",["north east","northeast","north-east"],
   "North East lies halfway between North and East."),
 F("P5",24,"Environment","Conservation","Medium",
   "Planting trees in an area where there were no trees before is called ______.",["afforestation"],
   "Afforestation is planting new forest; replanting a cut forest is reafforestation."),
 M("P5",25,"Environment","Wetlands","Hard",
   "Why should swamps be protected?",
   ["They dry up the land","They filter water and hold it during dry seasons","They cause drought","They kill all fish"],"B",
   "Wetlands clean water, store it and are home to many living things."),
 M("P5",26,"Social Services","Government ministries","Medium",
   "Which ministry is responsible for schools in Uganda?",
   ["Ministry of Health","Ministry of Education and Sports","Ministry of Works","Ministry of Agriculture"],"B",
   "The Ministry of Education and Sports runs education in Uganda."),
 T("P5",27,"Social Services","Health services","Easy",
   "A dispensary is one of the places where people get health services.","A",
   "Dispensaries, health centres and hospitals all provide health services."),
 F("P5",28,"Transport","Railway","Medium",
   "The railway line built from Mombasa towards Kampala is called the ______ Railway.",["uganda"],
   "It was named the Uganda Railway although it started at Mombasa."),
 F("P5",29,"Trade","Imports and exports","Medium",
   "Buying goods from other countries is called ______.",["importation","importing","imports"],
   "Importation is buying from abroad; exportation is selling abroad."),
 P("P5",30,"Physical Features","Location of features","Hard",
   "Match each physical feature with where it is found.",
   [["Mount Elgon","Eastern Uganda"],["Mount Rwenzori","Western Uganda"],
    ["Lake Bunyonyi","Kabale"],["Source of the Nile","Jinja"]],
   "Knowing where features are helps you read maps of Uganda."),
 M("P5",31,"Agriculture","Soil conservation","Hard",
   "A farmer on a steep hill is losing soil whenever it rains. What should he do?",
   ["Burn the grass","Dig terraces across the slope","Graze more animals","Leave the land bare"],"B",
   "Terraces slow down running water so it cannot wash away soil.","scenario"),
 M("P5",32,"Natural Resources","Uses","Medium",
   "Which one is a renewable natural resource?",
   ["Copper","Limestone","Forests","Petroleum"],"C",
   "Forests can grow again if replanted. Minerals cannot be replaced."),
]

# ══════════════════════════════════════════════════════════════════════════
# P.6 — East Africa, industry, urbanisation, government, regional history.
# ══════════════════════════════════════════════════════════════════════════
P6 = [
 M("P6",1,"East Africa","Uganda's neighbours","Easy",
   "Which East African country lies between Uganda and the Indian Ocean?",
   ["Kenya","Rwanda","South Sudan","Burundi"],"A",
   "Kenya lies between Uganda and the Indian Ocean, which is why Uganda uses the port of Mombasa."),
 F("P6",2,"East Africa","Capital cities","Medium",
   "The official capital city of Tanzania is ______.",["dodoma"],
   "Dodoma is the official capital of Tanzania."),
 M("P6",3,"Physical Features","Lakes","Medium",
   "Which is the deepest lake in East Africa?",
   ["Lake Victoria","Lake Tanganyika","Lake Albert","Lake Kyoga"],"B",
   "Lake Tanganyika is the deepest lake in Africa and in East Africa."),
 M("P6",4,"Physical Features","Mountains","Easy",
   "Mount Kilimanjaro is found in ______.",["Kenya","Tanzania","Uganda","Rwanda"],"B",
   "Kilimanjaro is in Tanzania and is Africa's highest mountain."),
 F("P6",5,"Physical Features","Rift Valley","Hard",
   "The Great Rift Valley enters East Africa in two branches: the Eastern branch and the ______ branch.",
   ["western"],"The Western branch holds lakes such as Albert, Edward and Tanganyika."),
 M("P6",6,"Drainage","Rivers","Medium",
   "Which river flows out of Lake Victoria?",["River Tana","River Nile","River Rufiji","River Pangani"],"B",
   "The Nile leaves Lake Victoria at Jinja and flows northwards."),
 M("P6",7,"Climate","Rainfall patterns","Hard",
   "Areas lying near the Equator usually receive rainfall ______.",
   ["Once a year","Twice a year","Only in December","Never"],"B",
   "Near the Equator there are two rainy seasons in a year."),
 M("P6",8,"Vegetation","Coastal vegetation","Medium",
   "Mangrove forests grow ______.",
   ["On mountain tops","Along the sea coast","In deserts","In rift valleys"],"B",
   "Mangroves grow in salty, muddy water along the coast."),
 M("P6",9,"Economic Activities","Cash crops","Medium",
   "Sisal is grown mainly in ______.",["Uganda","Tanzania","Rwanda","Burundi"],"B",
   "Tanzania, especially around Tanga, is known for sisal growing."),
 M("P6",10,"Industry","Types of industry","Medium",
   "Which industry turns cotton into cloth?",["Textile","Cement","Brewing","Sugar"],"A",
   "Textile industries spin and weave cotton into cloth."),
 F("P6",11,"Trade","Types of trade","Medium",
   "Trade carried out between two or more countries is called ______ trade.",
   ["international","external","foreign"],"International trade crosses national borders."),
 F("P6",12,"Transport","Railways","Hard",
   "The TAZARA railway links Tanzania with ______.",["zambia"],
   "TAZARA runs from Dar es Salaam to Zambia."),
 M("P6",13,"Transport","Sea ports","Medium",
   "Which sea port handles most of Uganda's imports?",
   ["Mombasa","Dar es Salaam","Tanga","Mtwara"],"A",
   "Mombasa in Kenya is the nearest and busiest port for Uganda."),
 F("P6",14,"Population","Migration","Medium",
   "The movement of people from villages to towns is called rural-urban ______.",["migration"],
   "Rural-urban migration is people moving to towns, often to look for work."),
 M("P6",15,"Urbanisation","Effects","Hard",
   "What problem is most likely when too many people move into a town at once?",
   ["More farmland","Slums and congestion","Cleaner air","Fewer schools needed"],"B",
   "Fast growth without planning leads to crowding, slums and pressure on services.","cause_effect"),
 M("P6",16,"Government","Arms of government","Easy",
   "How many arms of government does Uganda have?",["Two","Three","Four","Five"],"B",
   "The three arms are the Legislature, the Executive and the Judiciary."),
 F("P6",17,"Government","Legislature","Medium",
   "The arm of government that makes laws is the ______.",["legislature","parliament"],
   "Parliament, the legislature, debates and passes laws."),
 M("P6",18,"Government","Judiciary","Medium",
   "Who heads the Judiciary in Uganda?",
   ["The Speaker","The Chief Justice","The Prime Minister","The Attorney General"],"B",
   "The Chief Justice is the head of the Judiciary."),
 M("P6",19,"Citizenship","Rights and duties","Hard",
   "Which one is a responsibility of a citizen rather than a right?",
   ["Right to education","Paying taxes","Right to life","Freedom of worship"],"B",
   "Rights are what you are entitled to; responsibilities are what you must do."),
 M("P6",20,"History","Uganda's independence","Medium",
   "Who became the first Prime Minister of independent Uganda?",
   ["Sir Edward Mutesa II","Apollo Milton Obote","Idi Amin","Benedicto Kiwanuka"],"B",
   "Milton Obote was Prime Minister when Uganda became independent in 1962."),
 F("P6",21,"History","Colonial agreements","Hard",
   "The Buganda Agreement between the British and Buganda was signed in the year ______.",["1900"],
   "The 1900 Buganda Agreement set out land and administration arrangements."),
 M("P6",22,"History","Explorers","Medium",
   "Which explorer reported the source of the River Nile in 1862?",
   ["Henry Morton Stanley","John Hanning Speke","David Livingstone","Samuel Baker"],"B",
   "Speke reached the point where the Nile leaves Lake Victoria in 1862."),
 F("P6",23,"History","Missionaries","Hard",
   "The first Church Missionary Society missionary to reach Buganda in 1877 was Alexander ______.",
   ["mackay"],"Alexander Mackay arrived in Buganda in 1877 and taught reading and crafts."),
 M("P6",24,"History","Kingdoms","Hard",
   "Which group replaced the Bachwezi as rulers of Bunyoro-Kitara?",
   ["The Babiito","The Bahinda","The Baganda","The Basoga"],"A",
   "The Babiito, of Luo origin, took over from the Bachwezi in Bunyoro-Kitara."),
 F("P6",25,"East African Community","EAC organs","Medium",
   "The headquarters of the East African Community is at ______ in Tanzania.",["arusha"],
   "The EAC Secretariat is based in Arusha."),
 M("P6",26,"East African Community","Membership","Hard",
   "Which country was one of the three founder members of the East African Community in 1967?",
   ["Rwanda","Burundi","Kenya","South Sudan"],"C",
   "Kenya, Uganda and Tanzania formed the first EAC in 1967."),
 M("P6",27,"Map Work","Grid references","Hard",
   "What is a grid reference used for on a map?",
   ["Measuring temperature","Locating an exact place","Drawing the scale","Showing colours"],"B",
   "Grid references use numbered lines to give the exact position of a place.","map_skill"),
 M("P6",28,"Map Work","Map symbols","Medium",
   "On most maps, blue colour is used to show ______.",
   ["Forests","Water bodies","Mountains","Roads"],"B",
   "Blue shows lakes, rivers and other water bodies.","map_skill"),
 F("P6",29,"Map Work","Direction","Hard",
   "The direction directly opposite South West is ______.",["north east","northeast","north-east"],
   "Opposite directions are always 180° apart: SW and NE.","map_skill"),
 M("P6",30,"Environment","Soil erosion","Hard",
   "Which activity most increases soil erosion on hillsides?",
   ["Terracing","Overgrazing","Mulching","Planting cover crops"],"B",
   "Overgrazing leaves the soil bare so rain washes it away.","cause_effect"),
 P("P6",31,"East Africa","Capital cities","Medium",
   "Match each East African country with its capital city.",
   [["Kenya","Nairobi"],["Rwanda","Kigali"],["South Sudan","Juba"],["Uganda","Kampala"]],
   "Knowing capitals helps you locate countries and understand regional links."),
 M("P6",32,"Community Development","Problem solving","Hard",
   "Farmers in a district cannot get their produce to market because the roads are poor. What is the best solution?",
   ["Stop farming","Repair and maintain the feeder roads","Increase taxes on farmers","Move everyone to the city"],"B",
   "Good feeder roads let farmers reach markets and earn more.","scenario"),
]

# ══════════════════════════════════════════════════════════════════════════
# P.7 — PLE-style. Original questions on the same curriculum knowledge.
# ══════════════════════════════════════════════════════════════════════════
P7 = [
 # GEOGRAPHY
 F("P7",1,"Geography","Location of Uganda","Easy",
   "Uganda lies between 4°N and 1°S, which means it is crossed by the ______.",["equator"],
   "The Equator (0°) passes through southern Uganda.",code="GEO"),
 M("P7",2,"Geography","Physical Features","Medium",
   "Which of these features was formed by faulting?",
   ["Mount Elgon","Lake Albert","Lake Victoria","Mount Muhavura"],"B",
   "Lake Albert lies in the Rift Valley, formed when land sank between faults.",code="GEO"),
 F("P7",3,"Geography","Physical Features","Medium",
   "Mount Elgon and Mount Muhavura were both formed by ______ activity.",["volcanic","vulcanicity"],
   "They are volcanic mountains built from material thrown out of the earth.",code="GEO"),
 M("P7",4,"Geography","Lakes","Hard",
   "Which is the deepest lake in Uganda?",
   ["Lake Victoria","Lake Bunyonyi","Lake Albert","Lake Kyoga"],"B",
   "Lake Bunyonyi in Kabale is the deepest lake in Uganda.",code="GEO"),
 M("P7",5,"Geography","Climate","Hard",
   "Why does Kabale receive more rainfall than Moroto?",
   ["Kabale is nearer the sea","Kabale is higher and receives relief rainfall",
    "Kabale has more people","Moroto has more forests"],"B",
   "High land forces moist air to rise, cool and fall as relief rainfall.",
   "cause_effect",code="GEO"),
 M("P7",6,"Geography","Population","Hard",
   "Why are the shores of Lake Victoria densely populated?",
   ["The climate is very cold","There is reliable rainfall, fishing and fertile soil",
    "The soils are poor","There is very little water"],"B",
   "Reliable rain, fish and fertile soils support many people.",
   "cause_effect",code="GEO"),
 M("P7",7,"Geography","Agriculture","Medium",
   "What most limits crop growing in the Karamoja region?",
   ["Very fertile soils","Low and unreliable rainfall","Too many rivers","Very cold weather"],"B",
   "Karamoja is semi-arid, so crops often fail without irrigation.",code="GEO"),
 M("P7",8,"Geography","Tourism","Medium",
   "Which national park is best known for mountain gorillas?",
   ["Murchison Falls","Bwindi Impenetrable","Kidepo Valley","Lake Mburo"],"B",
   "Bwindi Impenetrable National Park protects mountain gorillas.",code="GEO"),
 M("P7",9,"Geography","Industry","Hard",
   "Which raw material is used by the cement factories at Hima and Tororo?",
   ["Copper","Limestone","Cotton","Timber"],"B",
   "Cement is made mainly from limestone.",code="GEO"),
 M("P7",10,"Geography","Energy","Hard",
   "Why is the River Nile at Jinja suitable for generating hydro-electric power?",
   ["It flows very slowly","It has a steady flow and a fall in the land",
    "It has salty water","It dries up in the dry season"],"B",
   "A constant flow plus a drop in level turns turbines all year.",
   "cause_effect",code="GEO"),
 M("P7",11,"Geography","Fishing","Medium",
   "Which problem most threatens fish stocks on Lake Victoria today?",
   ["Too much rain","Overfishing and use of illegal nets","Too many boats on land","Cold water"],"B",
   "Catching immature fish with illegal nets reduces future stocks.",code="GEO"),
 # MAP WORK
 F("P7",12,"Map Work","Direction","Easy",
   "A person facing North turns 180° clockwise. The new direction faced is ______.",["south"],
   "A half turn of 180° from North brings you to South.",code="MAP"),
 M("P7",13,"Map Work","Scale","Hard",
   "On a map with a scale of 1:100,000, a distance of 4 cm represents ______ on the ground.",
   ["4 kilometres","40 kilometres","400 metres","0.4 kilometres"],"A",
   "1 cm stands for 100,000 cm = 1 km, so 4 cm stands for 4 km.",
   "map_skill",code="MAP"),
 F("P7",14,"Map Work","Relief","Medium",
   "Lines drawn on a map to join places of the same height are called ______.",["contours","contour lines"],
   "Contours show the shape and height of the land.",code="MAP"),
 M("P7",15,"Map Work","Relief","Hard",
   "Contour lines drawn very close together show ______.",
   ["A gentle slope","A steep slope","Flat land","A lake"],"B",
   "The closer the contours, the steeper the slope.","map_skill",code="MAP"),
 M("P7",16,"Map Work","Grid references","Hard",
   "A six-figure grid reference locates a place to the nearest ______.",
   ["1 kilometre","100 metres","10 kilometres","1 metre"],"B",
   "Four figures give 1 km; six figures narrow it to 100 m.","map_skill",code="MAP"),
 M("P7",17,"Map Work","Map elements","Medium",
   "Which element of a map tells the reader what the map is about?",
   ["The key","The title","The scale","The compass"],"B",
   "The title states the subject and area of the map.","map_skill",code="MAP"),
 M("P7",18,"Map Work","Interpretation","Hard",
   "A map shows many buildings, a hospital, a school and tarmac roads close together. This area is most likely ______.",
   ["A forest reserve","An urban centre","A desert","A swamp"],"B",
   "Dense buildings and services are signs of a town.","map_skill",code="MAP"),
 # HISTORY
 F("P7",19,"History","Arab traders","Hard",
   "The first Arab trader to reach Buganda, Ahmed bin Ibrahim, arrived during the reign of Kabaka ______.",
   ["suna","suna ii"],"Ahmed bin Ibrahim reached Buganda in 1844 during Kabaka Suna II's reign.",code="HIST"),
 F("P7",20,"History","British influence","Medium",
   "Captain Frederick Lugard signed a treaty with Kabaka Mwanga in the year ______.",["1890"],
   "The 1890 treaty brought Buganda under the Imperial British East Africa Company.",code="HIST"),
 F("P7",21,"History","Independence","Easy",
   "Uganda attained her independence on 9th October ______.",["1962"],
   "Uganda became independent on 9th October 1962.",code="HIST"),
 M("P7",22,"History","Colonial administration","Hard",
   "Which system of administration did the British mainly use in Buganda?",
   ["Direct rule","Indirect rule","Assimilation","Association"],"B",
   "Indirect rule governed through existing chiefs and kings.",code="HIST"),
 F("P7",23,"History","Colonial administration","Hard",
   "The French governed their West African colonies using the policy of ______.",["assimilation"],
   "Assimilation aimed to make colonial subjects adopt French culture.",code="HIST"),
 M("P7",24,"History","African nationalism","Medium",
   "Who led Ghana to independence in 1957?",
   ["Julius Nyerere","Kwame Nkrumah","Jomo Kenyatta","Milton Obote"],"B",
   "Kwame Nkrumah led Ghana, the first African country south of the Sahara to be independent.",code="HIST"),
 M("P7",25,"History","Resistance","Hard",
   "The Maji Maji rebellion was fought against ______ rule in Tanganyika.",
   ["British","German","French","Portuguese"],"B",
   "The Maji Maji rebellion of 1905-1907 was against German rule.",code="HIST"),
 M("P7",26,"History","Colonial economy","Hard",
   "Why did many Africans resist paying colonial taxes?",
   ["They were very wealthy","Taxes were forced on them and they saw few benefits",
    "Taxes were optional","They wanted more taxes"],"B",
   "Taxes were compulsory, paid in cash, and returned little to the people.",
   "cause_effect",code="HIST"),
 M("P7",27,"History","Transport history","Hard",
   "What was the main reason for building the Uganda Railway?",
   ["To carry tourists","To ease movement of goods and administration to the interior",
    "To stop farming","To connect villages only"],"B",
   "The railway opened the interior for trade and colonial administration.",code="HIST"),
 M("P7",28,"History","Early people","Medium",
   "The discovery of which material marked the end of the Stone Age?",
   ["Copper","Iron","Gold","Salt"],"B",
   "Iron tools were stronger than stone and changed farming and warfare.",code="HIST"),
 # CIVICS
 F("P7",29,"Civics","Constitution","Medium",
   "The present Constitution of Uganda was promulgated in the year ______.",["1995"],
   "Uganda's current Constitution was promulgated in 1995.",code="CIV"),
 M("P7",30,"Civics","Arms of government","Medium",
   "Which arm of government interprets the law?",
   ["The Legislature","The Executive","The Judiciary","The Cabinet"],"C",
   "Courts under the Judiciary interpret and apply the law.",code="CIV"),
 M("P7",31,"Civics","Elections","Hard",
   "A by-election is held when ______.",
   ["The President travels","A parliamentary seat falls vacant before the next general election",
    "A law is passed","A new district is created"],"B",
   "A by-election fills a seat left vacant between general elections.",code="CIV"),
 M("P7",32,"Civics","Good governance","Medium",
   "Which one is a sign of good governance?",
   ["Corruption","Accountability","Nepotism","Tribalism"],"B",
   "Accountability means leaders explain how they use public resources.",code="CIV"),
 F("P7",33,"Civics","National symbols","Medium",
   "On the Uganda national flag, the black colour stands for the ______ of Africa.",["people"],
   "Black stands for the people, yellow for sunshine, red for brotherhood.",code="CIV"),
 M("P7",34,"Civics","Conflict resolution","Hard",
   "Two neighbouring villages disagree over the use of a water source. What is the best way to solve this?",
   ["Fighting over it","Dialogue and mediation by local leaders",
    "Blocking the water","Ignoring the problem"],"B",
   "Peaceful dialogue settles disputes without harming either side.",
   "scenario",code="CIV"),
 M("P7",35,"Civics","Local government","Hard",
   "Which local council level is closest to the people in a village?",
   ["LC I","LC III","LC V","Parliament"],"A",
   "LC I is the village council, the level nearest to the people.",code="CIV"),
 # EAST AFRICA
 M("P7",36,"East Africa","EAC organs","Hard",
   "What is the main work of the East African Legislative Assembly?",
   ["Making laws for the Community","Trying criminal cases","Collecting national taxes","Building roads"],"A",
   "EALA debates and passes laws for the East African Community.",code="EA"),
 M("P7",37,"East Africa","Regional cooperation","Medium",
   "Which one is a benefit Uganda gets from the East African Community?",
   ["A wider market for her goods","Higher transport costs","Fewer trading partners","More trade barriers"],"A",
   "A common market lets Ugandan goods sell freely across member states.",code="EA"),
 M("P7",38,"East Africa","Landlocked countries","Hard",
   "Uganda is a landlocked country. Which problem does this create?",
   ["She has no lakes","She depends on other countries' sea ports, raising costs",
    "She cannot grow crops","She has no neighbours"],"B",
   "Goods must travel overland to Mombasa or Dar es Salaam, adding cost and delay.",
   "cause_effect",code="EA"),
 # AFRICA
 F("P7",39,"Africa","Rivers","Easy",
   "The longest river in Africa is the River ______.",["nile"],
   "The Nile is the longest river in Africa.",code="AFR"),
 F("P7",40,"Africa","Deserts","Easy",
   "The largest desert in Africa is the ______ Desert.",["sahara"],
   "The Sahara stretches across northern Africa.",code="AFR"),
 M("P7",41,"Africa","Colonial history","Medium",
   "Which African country was never colonised?",
   ["Ghana","Ethiopia","Kenya","Nigeria"],"B",
   "Ethiopia kept her independence throughout the colonial period.",code="AFR"),
 F("P7",42,"Africa","Mountains","Easy",
   "The highest mountain in Africa is Mount ______.",["kilimanjaro"],
   "Kilimanjaro in Tanzania is Africa's highest mountain.",code="AFR"),
 M("P7",43,"Africa","Vegetation","Hard",
   "How does the vegetation of the Congo Basin differ from that of the Sahel?",
   ["The Congo Basin has dense rain forest while the Sahel has short grass and thorny scrub",
    "Both are deserts","The Congo Basin is desert","The Sahel has rain forest"],"A",
   "Heavy rainfall gives the Congo Basin thick forest; the dry Sahel supports only scrub.",
   "comparison",code="AFR"),
 M("P7",44,"Africa","Organisations","Medium",
   "Which organisation replaced the Organisation of African Unity?",
   ["The African Union","The Commonwealth","ECOWAS","SADC"],"A",
   "The African Union replaced the OAU in 2002.",code="AFR"),
 P("P7",45,"History","Historical figures","Hard",
   "Match each person with what they are remembered for in Uganda's history.",
   [["John Hanning Speke","Reported the source of the Nile"],
    ["Alexander Mackay","Early CMS missionary in Buganda"],
    ["Frederick Lugard","Signed the 1890 treaty with Kabaka Mwanga"],
    ["Milton Obote","First Prime Minister of independent Uganda"]],
   "Each figure played a different role in Uganda's history.",code="HIST"),
]

# ══════════════════════════════════════════════════════════════════════════
DATASETS = {"P4": P4, "P5": P5, "P6": P6, "P7": P7}
TITLES = {"P4": "Primary 4", "P5": "Primary 5", "P6": "Primary 6", "P7": "Primary 7"}

# ── load every batch in tools/batches/ ────────────────────────────────────
bdir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "batches")
for f in sorted(glob.glob(os.path.join(bdir, "*.py"))):
    spec = importlib.util.spec_from_file_location(os.path.basename(f)[:-3], f)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    first = getattr(mod, "EXTRA_FIRST", {})       # take the low ID numbers
    for cls, qs in first.items():
        DATASETS[cls][:0] = qs
    for cls, qs in getattr(mod, "EXTRA", {}).items():
        DATASETS[cls].extend(qs)
    added = {**{c: len(q) for c, q in first.items()},
             **{c: len(q) for c, q in getattr(mod, "EXTRA", {}).items()}}
    print(f"  + {os.path.basename(f)}: " + ", ".join(f"{c}+{n}" for c, n in added.items()))

# ── targets from the brief ────────────────────────────────────────────────
TARGET_TOTAL = 200
TARGET_DIFF = {"Easy": 70, "Medium": 80, "Hard": 50}

os.makedirs(OUT, exist_ok=True)
print()
rows, grand = [], 0
for cls in ("P4", "P5", "P6", "P7"):
    qs = DATASETS[cls]
    # ── de-duplicate, loudly ──────────────────────────────────────────────
    # An identical question must never be served twice. Anything skipped is
    # REPORTED here, never dropped in silence.
    import re as _re
    _norm = lambda t: _re.sub(r"[^a-z0-9 ]", "", t.lower()).strip()
    seen, kept, skipped = {}, [], []
    for q in qs:
        k = _norm(q["question"])
        if k in seen:
            skipped.append((q, seen[k]))
        else:
            seen[k] = q
            kept.append(q)
    if skipped:
        print(f"  ! {cls}: {len(skipped)} exact duplicate(s) not served:")
        for q, first in skipped:
            print(f"      '{q['question'][:58]}'")
    qs = kept
    DATASETS[cls] = qs

    # ── ID allocation ─────────────────────────────────────────────────────
    # Owner-supplied batches own 001-500 so successive batches stay contiguous
    # (batch 1 = 001-100, batch 2 = 101-200, ...). App-generated questions are
    # parked at 501+ so they can never block that run.
    owner = [q for q in qs if q.get("origin")]
    gen = [q for q in qs if not q.get("origin")]
    if owner:
        for i, q in enumerate(owner, 1):
            q["id"] = f"{cls}_SST_{i:03d}"
        for i, q in enumerate(gen, 1):
            q["id"] = f"{cls}_SST_G{i:03d}"   # G = app-generated, never collides
        qs = owner + gen
        DATASETS[cls] = qs
    else:
        for i, q in enumerate(qs, 1):
            q["id"] = f"{cls}_SST_{i:03d}"

    topics = {}
    for q in qs:
        topics.setdefault(q["topic"], set()).add(q["subtopic"])
    doc = {"class": cls, "className": TITLES[cls], "subject": "SST",
           "curriculum": "Uganda primary Social Studies",
           "levels": {"1": "Beginner", "2": "Intermediate", "3": "Advanced"},
           "target": {"total": TARGET_TOTAL, "difficulty": TARGET_DIFF},
           "topics": {t: sorted(v) for t, v in sorted(topics.items())},
           "total": len(qs), "questions": qs}
    with open(f"{OUT}/sst-{cls.lower()}.json", "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, ensure_ascii=False)
    d = {k: sum(1 for q in qs if q["difficulty"] == k) for k in TARGET_DIFF}
    rows.append((cls, len(qs), d, len(topics)))
    grand += len(qs)

print(f"{'CLASS':6}{'HAVE':>6}{'TARGET':>8}{'GAP':>6}   {'EASY':>10} {'MEDIUM':>10} {'HARD':>10}   TOPICS")
for cls, n, d, t in rows:
    gap = TARGET_TOTAL - n
    e = f"{d['Easy']}/{TARGET_DIFF['Easy']}"
    m = f"{d['Medium']}/{TARGET_DIFF['Medium']}"
    h = f"{d['Hard']}/{TARGET_DIFF['Hard']}"
    print(f"{cls:6}{n:>6}{TARGET_TOTAL:>8}{gap:>6}   {e:>10} {m:>10} {h:>10}   {t:>6}")
print(f"\n{'TOTAL':6}{grand:>6}{800:>8}{800-grand:>6}")
print(f"\nProgress to the 800-question target: {grand/800*100:.0f}%")
